require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const { db } = require('../config/firebase');

const trad = (id, nombre, contexto, es, en, no, fr, ca, da) =>
  db.collection('traducciones').doc(String(id)).set(
    { id_texto: id, nombre_texto: nombre, contexto, version: '1.0.0',
      traducciones: { es, en, no, fr, ca, da } },
    { merge: true },
  );

async function migrate() {
  console.log('Migrando traducciones de pantallas internas de herramientas (IDs 217-390)...');

  await Promise.all([
    // ── Shared UI ──────────────────────────────────────────────────────────
    trad(217, 'ui.si',       'ui', 'Sí',        'Yes',       'Ja',      'Oui',      'Sí',         'Ja'),
    trad(218, 'ui.no',       'ui', 'No',         'No',        'Nei',     'Non',      'No',         'Nej'),
    trad(219, 'ui.cancelar', 'ui', 'Cancelar',   'Cancel',    'Avbryt',  'Annuler',  'Cancel·lar', 'Annuller'),
    trad(220, 'ui.guardar',  'ui', 'Guardar',    'Save',      'Lagre',   'Enregistrer', 'Desar',   'Gem'),

    // ── H1 Asistente 112 ───────────────────────────────────────────────────
    trad(221, 'herramienta.1.llamar_112',       'herramienta', 'Llamar al 112',   'Call 112',             'Ring 112',                      'Appeler le 112',           'Trucar al 112',              'Ring 112'),
    trad(222, 'herramienta.1.ubicacion_titulo', 'herramienta', 'Tu ubicación actual', 'Your current location', 'Din nåværende plassering',  'Votre position actuelle',  'La teva ubicació actual',    'Din aktuelle placering'),
    trad(223, 'herramienta.1.gps_cargando',     'herramienta', 'Obteniendo ubicación...', 'Getting location...', 'Henter plassering...', 'Obtention de la position...', 'Obtenint ubicació...', 'Henter placering...'),
    trad(224, 'herramienta.1.gps_ok_titulo',    'herramienta', 'Ubicación obtenida', 'Location obtained', 'Plassering hentet', 'Position obtenue', 'Ubicació obtinguda', 'Placering hentet'),
    trad(225, 'herramienta.1.gps_coords_hint',  'herramienta',
      'Comparte estas coordenadas con el 112 si no puedes describir tu ubicación.',
      'Share these coordinates with 112 if you cannot describe your location.',
      'Del disse koordinatene med 112 hvis du ikke kan beskrive plasseringen din.',
      'Partagez ces coordonnées avec le 112 si vous ne pouvez pas décrire votre position.',
      'Comparteix aquestes coordenades amb el 112 si no pots descriure la teva ubicació.',
      'Del disse koordinater med 112, hvis du ikke kan beskrive din placering.'),
    trad(226, 'herramienta.1.copiar_coords',    'herramienta', 'Copiar coordenadas', 'Copy coordinates', 'Kopier koordinater', 'Copier les coordonnées', 'Copiar coordenades', 'Kopiér koordinater'),
    trad(227, 'herramienta.1.coords_copiadas',  'herramienta', 'Coordenadas copiadas', 'Coordinates copied', 'Koordinater kopiert', 'Coordonnées copiées', 'Coordenades copiades', 'Koordinater kopieret'),
    trad(228, 'herramienta.1.ver_mapa',         'herramienta', 'Ver en el mapa', 'View on map', 'Se på kart', 'Voir sur la carte', 'Veure al mapa', 'Se på kort'),
    trad(229, 'herramienta.1.actualizar',       'herramienta', 'Actualizar', 'Refresh', 'Oppdater', 'Actualiser', 'Actualitzar', 'Opdater'),
    trad(230, 'herramienta.1.gps_denegado_titulo', 'herramienta', 'Permiso de ubicación denegado', 'Location permission denied', 'Posisjonstillatelse nektet', 'Permission de localisation refusée', "Permís d'ubicació denegat", 'Placeringsgodkendelse nægtet'),
    trad(231, 'herramienta.1.gps_denegado_desc', 'herramienta',
      'Accede a Ajustes del dispositivo y activa los permisos de ubicación para esta app.',
      'Go to device Settings and enable location permissions for this app.',
      'Gå til enhetsinnstillinger og aktiver plasseringstillatelser for denne appen.',
      "Accédez aux paramètres de l'appareil et activez les autorisations de localisation pour cette application.",
      "Accedeix a Configuració del dispositiu i activa els permisos d'ubicació per a aquesta app.",
      'Gå til enhedsindstillinger og aktivér placeringsgodkendelser for denne app.'),
    trad(232, 'herramienta.1.gps_error_titulo', 'herramienta', 'No se pudo obtener la ubicación', 'Could not get location', 'Kunne ikke hente plassering', "Impossible d'obtenir la position", "No s'ha pogut obtenir la ubicació", 'Kunne ikke hente placering'),
    trad(233, 'herramienta.1.gps_error_desc',   'herramienta', 'Asegúrate de que el GPS está activo.', 'Make sure GPS is enabled.', 'Sørg for at GPS er aktivert.', 'Assurez-vous que le GPS est activé.', "Assegura't que el GPS està actiu.", 'Sørg for, at GPS er aktiveret.'),
    trad(234, 'herramienta.1.reintentar',        'herramienta', 'Intentar de nuevo', 'Try again', 'Prøv igjen', 'Réessayer', 'Tornar a intentar', 'Prøv igen'),
    trad(235, 'herramienta.1.abrir_ajustes',    'herramienta', 'Abrir ajustes', 'Open settings', 'Åpne innstillinger', 'Ouvrir les paramètres', 'Obrir ajustos', 'Åbn indstillinger'),
    trad(236, 'herramienta.1.info_titulo',      'herramienta', 'Información a comunicar al 112', 'Information to communicate to 112', 'Informasjon som skal kommuniseres til 112', 'Informations à communiquer au 112', 'Informació a comunicar al 112', 'Information til at kommunikere til 112'),
    trad(237, 'herramienta.1.campo_personas',   'herramienta', 'Número de personas afectadas', 'Number of people affected', 'Antall berørte personer', 'Nombre de personnes affectées', 'Nombre de persones afectades', 'Antal berørte personer'),
    trad(238, 'herramienta.1.campo_edad',       'herramienta', 'Edad aproximada', 'Approximate age', 'Omtrentlig alder', 'Âge approximatif', 'Edat aproximada', 'Omtrentlig alder'),
    trad(239, 'herramienta.1.campo_consciente', 'herramienta', '¿Está consciente?', 'Is the person conscious?', 'Er personen bevisst?', 'La personne est-elle consciente ?', 'Està conscient?', 'Er personen bevidst?'),
    trad(240, 'herramienta.1.campo_respira',    'herramienta', '¿Está respirando?', 'Is the person breathing?', 'Puster personen?', 'La personne respire-t-elle ?', 'Està respirant?', 'Trækker personen vejret?'),
    trad(241, 'herramienta.1.campo_lesiones',   'herramienta', 'Lesiones visibles', 'Visible injuries', 'Synlige skader', 'Blessures visibles', 'Lesions visibles', 'Synlige skader'),
    trad(242, 'herramienta.1.campo_sintomas',   'herramienta', 'Síntomas que refiere la víctima', 'Symptoms reported by the victim', 'Symptomer rapportert av offeret', 'Symptômes rapportés par la victime', 'Símptomes que refereix la víctima', 'Symptomer rapporteret af offeret'),
    trad(243, 'herramienta.1.campo_historial',  'herramienta', 'Historial médico relevante (si se conoce)', 'Relevant medical history (if known)', 'Relevant sykehistorie (om kjent)', 'Antécédents médicaux pertinents (si connus)', 'Historial mèdic rellevant (si es coneix)', 'Relevant sygehistorie (hvis kendt)'),
    trad(244, 'herramienta.1.resumen_titulo',   'herramienta', 'Qué decir al 112', 'What to say to 112', 'Hva du skal si til 112', 'Que dire au 112', 'Què dir al 112', 'Hvad man skal sige til 112'),
    trad(245, 'herramienta.1.resumen_texto',    'herramienta',
      '1. Tu ubicación exacta o las coordenadas GPS\n2. Qué ha pasado y cuántas personas están afectadas\n3. Estado de la víctima (consciente, respira)\n4. Lesiones visibles y síntomas\n5. Tu nombre y teléfono de contacto',
      '1. Your exact location or GPS coordinates\n2. What happened and how many people are affected\n3. Victim\'s condition (conscious, breathing)\n4. Visible injuries and symptoms\n5. Your name and contact phone number',
      '1. Din nøyaktige plassering eller GPS-koordinater\n2. Hva som skjedde og hvor mange som er berørt\n3. Offerets tilstand (bevisst, puster)\n4. Synlige skader og symptomer\n5. Ditt navn og kontakttelefonnummer',
      '1. Votre position exacte ou les coordonnées GPS\n2. Ce qui s\'est passé et combien de personnes sont affectées\n3. État de la victime (consciente, respire)\n4. Blessures visibles et symptômes\n5. Votre nom et numéro de téléphone de contact',
      '1. La teva ubicació exacta o les coordenades GPS\n2. Que ha passat i quantes persones estan afectades\n3. Estat de la víctima (conscient, respira)\n4. Lesions visibles i símptomes\n5. El teu nom i telèfon de contacte',
      '1. Din nøjagtige placering eller GPS-koordinater\n2. Hvad der skete og hvor mange mennesker der er berørt\n3. Offerets tilstand (bevidst, trækker vejret)\n4. Synlige skader og symptomer\n5. Dit navn og kontakttelefonummer'),

    // ── H2 Asistente RCP ───────────────────────────────────────────────────
    trad(246, 'herramienta.2.ritmo',              'herramienta', 'Ritmo: 110 compresiones/minuto', 'Rhythm: 110 compressions/minute', 'Rytme: 110 kompresjoner/minutt', 'Rythme : 110 compressions/minute', 'Ritme: 110 compressions/minut', 'Rytme: 110 kompressioner/minut'),
    trad(247, 'herramienta.2.instrucciones_titulo','herramienta', 'Instrucciones de RCP', 'CPR Instructions', 'HLR-instruksjoner', 'Instructions de RCP', 'Instruccions de RCP', 'HLR-instruktioner'),
    trad(248, 'herramienta.2.pasos',              'herramienta',
      'Coloca a la persona en una superficie dura y plana\nColoca tus manos entrelazadas en el centro del pecho\nComprime con los brazos rectos, profundidad 5-6 cm\nSigue el ritmo del metrónomo: 110 compresiones/min\nCada 30 compresiones, da 2 ventilaciones si estás entrenado',
      'Place the person on a hard, flat surface\nPlace your interlocked hands in the center of the chest\nCompress with straight arms, depth 5-6 cm\nFollow the metronome rhythm: 110 compressions/min\nEvery 30 compressions, give 2 breaths if trained',
      'Legg personen på en hard og flat overflate\nPlasser hendene dine sammenlåst midt på brystkassen\nKomprimer med rette armer, dybde 5-6 cm\nFølg metronomerytmen: 110 kompresjoner/min\nFor hver 30 kompresjoner, gi 2 innblåsinger hvis du er trent',
      'Placez la personne sur une surface dure et plate\nPlacez vos mains entrelacées au centre de la poitrine\nComprimez avec les bras droits, profondeur 5-6 cm\nSuivez le rythme du métronome : 110 compressions/min\nToutes les 30 compressions, donnez 2 ventilations si vous êtes formé',
      'Col·loca la persona en una superfície dura i plana\nCol·loca les teves mans entrellaçades al centre del pit\nComprimeix amb els braços rectes, profunditat 5-6 cm\nSegueix el ritme del metrònome: 110 compressions/min\nCada 30 compressions, fes 2 ventilacions si estàs entrenat',
      'Læg personen på en hård, flad overflade\nPlacer dine sammenfiltrede hænder i midten af brystet\nKomprimer med strakte arme, dybde 5-6 cm\nFølg metronomerytmen: 110 kompressioner/min\nFor hvert 30. kompression, giv 2 indblæsninger hvis du er uddannet'),
    trad(249, 'herramienta.2.compresiones_totales','herramienta', 'Compresiones\nTotales', 'Total\nCompressions', 'Totale\nKompresjoner', 'Compressions\nTotales', 'Compressions\nTotals', 'Totale\nKompressioner'),
    trad(250, 'herramienta.2.ciclos_completados', 'herramienta', 'Ciclos\nCompletados', 'Completed\nCycles', 'Fullførte\nSykluser', 'Cycles\nCompletés', 'Cicles\nCompletats', 'Gennemførte\nCyklusser'),
    trad(251, 'herramienta.2.ciclo_actual',        'herramienta', 'Ciclo Actual', 'Current Cycle', 'Nåværende syklus', 'Cycle actuel', 'Cicle actual', 'Aktuel cyklus'),
    trad(252, 'herramienta.2.pausar',              'herramienta', 'Pausar', 'Pause', 'Pause', 'Pause', 'Pausa', 'Pause'),
    trad(253, 'herramienta.2.iniciar',             'herramienta', 'Iniciar', 'Start', 'Start', 'Démarrer', 'Iniciar', 'Start'),
    trad(254, 'herramienta.2.aviso',               'herramienta',
      '⚠ Recuerda: Continúa la RCP hasta que llegue ayuda médica o la persona recupere la respiración.',
      '⚠ Remember: Continue CPR until medical help arrives or the person resumes breathing.',
      '⚠ Husk: Fortsett HLR til medisinsk hjelp ankommer eller personen begynner å puste igjen.',
      '⚠ Rappel : Continuez la RCP jusqu\'à l\'arrivée des secours médicaux ou la reprise de la respiration.',
      '⚠ Recorda: Continua la RCP fins que arribi ajuda mèdica o la persona recuperi la respiració.',
      '⚠ Husk: Fortsæt HLR, indtil medicinsk hjælp ankommer, eller personen genvinder vejrtrækning.'),

    // ── H3 Medidor FC ──────────────────────────────────────────────────────
    trad(255, 'herramienta.3.aviso_titulo',       'herramienta', 'Método manual de pulsación', 'Manual pulse method', 'Manuell pulsemetode', 'Méthode manuelle de pulsation', 'Mètode manual de pulsació', 'Manuel pulsmålingsmetode'),
    trad(256, 'herramienta.3.aviso_desc',         'herramienta',
      'Localiza el pulso en la muñeca o en el cuello. Pulsa el botón cada vez que notes un latido durante 15 segundos. La app calculará automáticamente las pulsaciones por minuto.',
      'Locate the pulse on the wrist or neck. Press the button each time you feel a heartbeat for 15 seconds. The app will automatically calculate beats per minute.',
      'Finn pulsen på håndleddet eller halsen. Trykk på knappen hver gang du kjenner et hjerteslag i 15 sekunder. Appen beregner automatisk slag per minutt.',
      'Localisez le pouls au poignet ou au cou. Appuyez sur le bouton chaque fois que vous sentez un battement pendant 15 secondes. L\'application calculera automatiquement les battements par minute.',
      'Localitza el pols al canell o al coll. Prem el botó cada cop que notis un batec durant 15 segons. L\'app calcularà automàticament les pulsacions per minut.',
      'Find pulsen på håndleddet eller halsen. Tryk på knappen, hver gang du mærker et hjerteslag i 15 sekunder. Appen beregner automatisk slag i minuttet.'),
    trad(257, 'herramienta.3.iniciar_medicion',   'herramienta', 'Iniciar medición (15 segundos)', 'Start measurement (15 seconds)', 'Start måling (15 sekunder)', 'Démarrer la mesure (15 secondes)', 'Iniciar mesura (15 segons)', 'Start måling (15 sekunder)'),
    trad(258, 'herramienta.3.instrucciones_titulo','herramienta', 'Cómo medir el pulso', 'How to measure the pulse', 'Slik måler du pulsen', 'Comment mesurer le pouls', 'Com mesurar el pols', 'Sådan måler du pulsen'),
    trad(259, 'herramienta.3.instrucciones_titulos','herramienta',
      'Localiza el pulso\nColoca tus dedos\nPulsa el botón\nEspera 15 segundos',
      'Locate the pulse\nPlace your fingers\nPress the button\nWait 15 seconds',
      'Finn pulsen\nPlasser fingrene dine\nTrykk på knappen\nVent 15 sekunder',
      'Localisez le pouls\nPlacez vos doigts\nAppuyez sur le bouton\nAttendez 15 secondes',
      'Localitza el pols\nCol·loca els dits\nPrem el botó\nEspera 15 segons',
      'Find pulsen\nPlacer dine fingre\nTryk på knappen\nVent 15 sekunder'),
    trad(260, 'herramienta.3.instrucciones_descs','herramienta',
      'En la muñeca (arteria radial) o en el cuello (arteria carótida)\nÍndice y corazón sobre la arteria. No uses el pulgar\nToca el botón grande cada vez que sientas un latido\nLa app calcula automáticamente al terminar el tiempo',
      'On the wrist (radial artery) or neck (carotid artery)\nIndex and middle finger on the artery. Do not use the thumb\nTap the large button every time you feel a heartbeat\nThe app calculates automatically when time is up',
      'På håndleddet (radialarterien) eller halsen (halsarterien)\nPeke- og langfinger på arterien. Ikke bruk tommelen\nTrykk på den store knappen hver gang du kjenner et hjerteslag\nAppen beregner automatisk når tiden er ute',
      'Au poignet (artère radiale) ou au cou (artère carotide)\nIndex et majeur sur l\'artère. N\'utilisez pas le pouce\nAppuyez sur le grand bouton chaque fois que vous sentez un battement\nL\'application calcule automatiquement à la fin du temps',
      'Al canell (artèria radial) o al coll (artèria caròtida)\nÍndex i cor sobre l\'artèria. No facis servir el polze\nToca el botó gran cada cop que sentis un batec\nL\'app calcula automàticament en acabar el temps',
      'På håndleddet (radialarterie) eller halsen (halspulsåre)\nPege- og langfinger på arterien. Brug ikke tommelfingeren\nTryk på den store knap, hver gang du mærker et hjerteslag\nAppen beregner automatisk, når tiden er gået'),
    trad(261, 'herramienta.3.taps_registrados',  'herramienta', 'Taps registrados', 'Taps recorded', 'Taps registrert', 'Taps enregistrés', 'Taps registrats', 'Taps registreret'),
    trad(262, 'herramienta.3.latido',            'herramienta', 'LATIDO', 'BEAT', 'SLAG', 'BATTEMENT', 'BATEC', 'SLAG'),
    trad(263, 'herramienta.3.pulsa_instruccion', 'herramienta', 'Pulsa el botón con cada latido que sientas', 'Press the button with each heartbeat you feel', 'Trykk på knappen med hvert hjerteslag du kjenner', 'Appuyez sur le bouton à chaque battement que vous ressentez', 'Prem el botó amb cada batec que sentis', 'Tryk på knappen ved hvert hjerteslag, du mærker'),
    trad(264, 'herramienta.3.bpm_estados',       'herramienta',
      'Muy bajo\nBajo\nNormal\nElevado\nMuy elevado',
      'Very low\nLow\nNormal\nElevated\nVery high',
      'Svært lav\nLav\nNormal\nForhøyet\nSvært høy',
      'Très bas\nBas\nNormal\nÉlevé\nTrès élevé',
      'Molt baix\nBaix\nNormal\nElevat\nMolt elevat',
      'Meget lav\nLav\nNormal\nForhøjet\nMeget høj'),
    trad(265, 'herramienta.3.bpm_descs',         'herramienta',
      'Frecuencia cardíaca muy baja. Busca atención médica inmediata.\nBradicardia. Si hay síntomas como mareo o dificultad respiratoria, consulta con un médico.\nFrecuencia cardíaca en rango normal en reposo (60-100 bpm).\nTaquicardia. Si no es por actividad física reciente, consulta con un médico.\nFrecuencia cardíaca muy alta. Busca atención médica si no es por ejercicio intenso.',
      'Very low heart rate. Seek immediate medical attention.\nBradycardia. If symptoms like dizziness or difficulty breathing occur, consult a doctor.\nHeart rate in normal resting range (60-100 bpm).\nTachycardia. If not due to recent physical activity, consult a doctor.\nVery high heart rate. Seek medical attention if not due to intense exercise.',
      'Svært lav hjertefrekvens. Oppsøk øyeblikkelig legehjelp.\nBradiakardi. Hvis symptomer som svimmelhet eller pustevansker oppstår, kontakt lege.\nHjertefrekvens i normalt hvileområde (60-100 bpm).\nTakykardi. Hvis ikke på grunn av nylig fysisk aktivitet, kontakt lege.\nSvært høy hjertefrekvens. Oppsøk legehjelp hvis ikke på grunn av intensiv trening.',
      'Fréquence cardiaque très basse. Consultez immédiatement un médecin.\nBradicardie. En cas de symptômes comme des vertiges ou des difficultés respiratoires, consultez un médecin.\nFréquence cardiaque dans la plage normale au repos (60-100 bpm).\nTachycardie. Si ce n\'est pas dû à une activité physique récente, consultez un médecin.\nFréquence cardiaque très élevée. Consultez un médecin si ce n\'est pas dû à un exercice intense.',
      'Freqüència cardíaca molt baixa. Busca atenció mèdica immediata.\nBradicàrdia. Si hi ha símptomes com mareig o dificultat respiratòria, consulta un metge.\nFreqüència cardíaca en rang normal en repòs (60-100 bpm).\nTaquicàrdia. Si no és per activitat física recent, consulta un metge.\nFreqüència cardíaca molt alta. Busca atenció mèdica si no és per exercici intens.',
      'Meget lav hjertefrekvens. Søg øjeblikkelig lægehjælp.\nBradykardi. Hvis symptomer som svimmelhed eller vejrtrækningsbesvær opstår, konsulter en læge.\nHjertefrekvens i normalt hvileinterval (60-100 bpm).\nTakykardi. Hvis ikke på grund af nylig fysisk aktivitet, konsulter en læge.\nMeget høj hjertefrekvens. Søg lægehjælp, hvis det ikke skyldes intens træning.'),
    trad(266, 'herramienta.3.medir_de_nuevo',    'herramienta', 'Medir de nuevo', 'Measure again', 'Mål igjen', 'Mesurer à nouveau', 'Mesurar de nou', 'Mål igen'),
    trad(267, 'herramienta.3.valores_titulo',    'herramienta', 'Valores de referencia (adultos en reposo)', 'Reference values (resting adults)', 'Referanseverdier (voksne i hvile)', 'Valeurs de référence (adultes au repos)', 'Valors de referència (adults en repòs)', 'Referenceværdier (voksne i hvile)'),
    trad(268, 'herramienta.3.valores_labels',    'herramienta',
      'Bradicardia\nNormal en reposo\nTaquicardia\nUrgente',
      'Bradycardia\nNormal at rest\nTachycardia\nUrgent',
      'Bradykardi\nNormal i hvile\nTakykardi\nHaster',
      'Bradycardie\nNormal au repos\nTachycardie\nUrgent',
      'Bradicàrdia\nNormal en repòs\nTaquicàrdia\nUrgent',
      'Bradykardi\nNormal i hvile\nTakykardi\nUrgent'),
    trad(269, 'herramienta.3.medicion_orientativa','herramienta',
      'ℹ Medición orientativa. Para diagnóstico usa dispositivos médicos certificados.',
      'ℹ Indicative measurement. For diagnosis use certified medical devices.',
      'ℹ Veiledende måling. For diagnose bruk sertifiserte medisinske enheter.',
      'ℹ Mesure indicative. Pour le diagnostic, utilisez des dispositifs médicaux certifiés.',
      'ℹ Mesura orientativa. Per a diagnòstic usa dispositius mèdics certificats.',
      'ℹ Vejledende måling. Brug certificerede medicinske apparater til diagnostik.'),
    trad(270, 'herramienta.3.seg',               'herramienta', 'seg', 's', 's', 's', 's', 's'),

    // ── H4 Test FAST ───────────────────────────────────────────────────────
    trad(271, 'herramienta.4.aviso',             'herramienta',
      'Método FAST\nEl método FAST es una forma rápida de identificar un posible Ictus. Cada minuto cuenta. Si detectas algún síntoma, llama inmediatamente al 112.',
      'FAST Method\nThe FAST method is a quick way to identify a possible stroke. Every minute counts. If you detect any symptom, call 112 immediately.',
      'FAST-metoden\nFAST-metoden er en rask måte å identifisere et mulig hjerneslag på. Hvert minutt teller. Hvis du oppdager et symptom, ring 112 umiddelbart.',
      'Méthode FAST\nLa méthode FAST est un moyen rapide d\'identifier un possible AVC. Chaque minute compte. Si vous détectez un symptôme, appelez le 112 immédiatement.',
      'Mètode FAST\nEl mètode FAST és una forma ràpida d\'identificar un possible ictus. Cada minut compta. Si detectes algun símptoma, truca immediatament al 112.',
      'FAST-metoden\nFAST-metoden er en hurtig måde at identificere et muligt slagtilfælde på. Hvert minut tæller. Hvis du opdager et symptom, ring 112 øjeblikkeligt.'),
    trad(272, 'herramienta.4.pregunta.F.titulo', 'herramienta', 'F - Face (Cara)', 'F - Face', 'F - Face (Ansikt)', 'F - Face (Visage)', 'F - Face (Cara)', 'F - Face (Ansigt)'),
    trad(273, 'herramienta.4.pregunta.F.desc',   'herramienta',
      'Pide a la persona que sonría. ¿Observas asimetría en la cara? ¿Un lado de la boca cae?',
      'Ask the person to smile. Do you see asymmetry in the face? Does one side of the mouth droop?',
      'Be personen smile. Ser du asymmetri i ansiktet? Henger den ene siden av munnen?',
      'Demandez à la personne de sourire. Observez-vous une asymétrie du visage ? Un côté de la bouche s\'affaisse-t-il ?',
      'Demana a la persona que somrigui. Observes asimetria a la cara? Cau un costat de la boca?',
      'Bed personen om at smile. Ser du asymmetri i ansigtet? Hænger den ene mundvig?'),
    trad(274, 'herramienta.4.pregunta.F.si',     'herramienta', 'Sí, hay asimetría', 'Yes, there is asymmetry', 'Ja, det er asymmetri', 'Oui, il y a asymétrie', 'Sí, hi ha asimetria', 'Ja, der er asymmetri'),
    trad(275, 'herramienta.4.pregunta.F.no',     'herramienta', 'No, es simétrica', 'No, it is symmetrical', 'Nei, det er symmetrisk', 'Non, c\'est symétrique', 'No, és simètrica', 'Nej, den er symmetrisk'),
    trad(276, 'herramienta.4.pregunta.A.titulo', 'herramienta', 'A - Arms (Brazos)', 'A - Arms', 'A - Arms (Armer)', 'A - Arms (Bras)', 'A - Arms (Braços)', 'A - Arms (Arme)'),
    trad(277, 'herramienta.4.pregunta.A.desc',   'herramienta',
      'Pide que levante ambos brazos con las palmas hacia arriba. ¿Un brazo cae o deriva hacia abajo?',
      'Ask them to raise both arms with palms facing up. Does one arm drop or drift downward?',
      'Be dem løfte begge armene med håndflatene opp. Faller eller driver én arm nedover?',
      'Demandez-lui de lever les deux bras, paumes vers le haut. Un bras tombe-t-il ou dérive-t-il vers le bas ?',
      'Demana que aixequi ambdós braços amb les palmes cap amunt. Un braç cau o deriva cap avall?',
      'Bed dem løfte begge arme med håndfladerne opad. Falder eller driver den ene arm nedad?'),
    trad(278, 'herramienta.4.pregunta.A.si',     'herramienta', 'Sí, un brazo cae', 'Yes, one arm drops', 'Ja, en arm faller', 'Oui, un bras tombe', 'Sí, un braç cau', 'Ja, en arm falder'),
    trad(279, 'herramienta.4.pregunta.A.no',     'herramienta', 'No, ambos se mantienen', 'No, both stay up', 'Nei, begge holdes oppe', 'Non, les deux se maintiennent', 'No, ambdós es mantenen', 'Nej, begge holdes oppe'),
    trad(280, 'herramienta.4.pregunta.S.titulo', 'herramienta', 'S - Speech (Habla)', 'S - Speech', 'S - Speech (Tale)', 'S - Speech (Parole)', 'S - Speech (Parla)', 'S - Speech (Tale)'),
    trad(281, 'herramienta.4.pregunta.S.desc',   'herramienta',
      'Pide que repita una frase sencilla. ¿Arrastra las palabras o no puede hablar correctamente?',
      'Ask them to repeat a simple sentence. Do they slur their words or have difficulty speaking?',
      'Be dem gjenta en enkel setning. Snakker de utydelig eller har de vanskeligheter med å snakke?',
      'Demandez-lui de répéter une phrase simple. Traîne-t-il les mots ou a-t-il du mal à parler correctement ?',
      'Demana que repeteixi una frase senzilla. Arrossega les paraules o no pot parlar correctament?',
      'Bed dem gentage en enkel sætning. Slører de ordene eller har svært ved at tale korrekt?'),
    trad(282, 'herramienta.4.pregunta.S.si',     'herramienta', 'Sí, habla con dificultad', 'Yes, speech is impaired', 'Ja, talen er svekket', 'Oui, la parole est altérée', 'Sí, parla amb dificultat', 'Ja, talen er forringet'),
    trad(283, 'herramienta.4.pregunta.S.no',     'herramienta', 'No, habla con normalidad', 'No, speech is normal', 'Nei, talen er normal', 'Non, la parole est normale', 'No, parla amb normalitat', 'Nej, talen er normal'),
    trad(284, 'herramienta.4.pregunta.T.titulo', 'herramienta', 'T - Time (Tiempo)', 'T - Time', 'T - Time (Tid)', 'T - Time (Temps)', 'T - Time (Temps)', 'T - Time (Tid)'),
    trad(285, 'herramienta.4.pregunta.T.desc',   'herramienta',
      '¿Los síntomas aparecieron de forma repentina en las últimas horas?',
      'Did the symptoms appear suddenly in the last few hours?',
      'Dukket symptomene opp plutselig de siste timene?',
      'Les symptômes sont-ils apparus soudainement au cours des dernières heures ?',
      'Els símptomes van aparèixer de forma sobtada en les darreres hores?',
      'Opstod symptomerne pludseligt inden for de seneste timer?'),
    trad(286, 'herramienta.4.pregunta.T.si',     'herramienta', 'Sí, aparecieron de repente', 'Yes, appeared suddenly', 'Ja, de dukket opp plutselig', 'Oui, sont apparus soudainement', 'Sí, van aparèixer de cop', 'Ja, opstod pludseligt'),
    trad(287, 'herramienta.4.pregunta.T.no',     'herramienta', 'No, son síntomas graduales', 'No, symptoms are gradual', 'Nei, symptomene er gradvise', 'Non, ce sont des symptômes progressifs', 'No, són símptomes graduals', 'Nej, symptomerne er gradvise'),
    trad(288, 'herramienta.4.resultado.ictus',   'herramienta', 'POSIBLE ICTUS', 'POSSIBLE STROKE', 'MULIG HJERNESLAG', 'AVC POSSIBLE', 'POSSIBLE ICTUS', 'MULIGT SLAGTILFÆLDE'),
    trad(289, 'herramienta.4.resultado.no_ictus','herramienta', 'Sin síntomas de ictus', 'No stroke symptoms', 'Ingen hjerneslagsymptomer', 'Aucun symptôme d\'AVC', 'Sense símptomes d\'ictus', 'Ingen slagtilfælde-symptomer'),
    trad(290, 'herramienta.4.resultado.ictus_desc','herramienta',
      'Se han detectado uno o más síntomas. Llama al 112 INMEDIATAMENTE. El tiempo es crítico.',
      'One or more symptoms have been detected. Call 112 IMMEDIATELY. Time is critical.',
      'Ett eller flere symptomer er oppdaget. Ring 112 UMIDDELBART. Tid er kritisk.',
      'Un ou plusieurs symptômes ont été détectés. Appelez le 112 IMMÉDIATEMENT. Le temps est critique.',
      "S'han detectat un o més símptomes. Truca al 112 IMMEDIATAMENT. El temps és crític.",
      'Et eller flere symptomer er opdaget. Ring 112 ØJEBLIKKELIGT. Tid er kritisk.'),
    trad(291, 'herramienta.4.resultado.no_ictus_desc','herramienta',
      'No se han detectado síntomas de ictus en este momento. Si tienes dudas, consulta con un médico.',
      'No stroke symptoms detected at this time. If in doubt, consult a doctor.',
      'Ingen hjerneslagsymptomer oppdaget akkurat nå. Kontakt lege ved tvil.',
      "Aucun symptôme d'AVC détecté pour le moment. En cas de doute, consultez un médecin.",
      "No s'han detectat símptomes d'ictus en aquest moment. Si tens dubtes, consulta un metge.",
      'Ingen slagtilfælde-symptomer opdaget på nuværende tidspunkt. Konsulter en læge ved tvivl.'),

    // ── H5 Calculadora Quemaduras ──────────────────────────────────────────
    trad(292, 'herramienta.5.aviso_titulo',        'herramienta', 'Regla de los 9', 'Rule of 9s', 'Ni-regelen', 'Règle des 9', 'Regla dels 9', '9-reglen'),
    trad(293, 'herramienta.5.aviso_desc',          'herramienta',
      'Esta calculadora usa la "Regla de los 9" para calcular el porcentaje de superficie corporal quemada en adultos.\n\nRegla de la palma: La palma de la mano de la víctima (sin el dedo pulgar) representa aproximadamente el 1% de su superficie corporal.',
      'This calculator uses the "Rule of 9s" to estimate the percentage of burned body surface area in adults.\n\nPalm rule: The victim\'s palm (excluding the thumb) represents approximately 1% of their body surface.',
      'Denne kalkulatoren bruker "Ni-regelen" for å beregne prosentandelen av forbrent kroppsoverflate hos voksne.\n\nHåndflateregel: Offerets håndflate (uten tommelen) utgjør omtrent 1% av kroppsoverflaten.',
      'Cette calculatrice utilise la "Règle des 9" pour estimer le pourcentage de surface corporelle brûlée chez les adultes.\n\nRègle de la paume : La paume de la victime (sans le pouce) représente environ 1% de sa surface corporelle.',
      'Aquesta calculadora usa la "Regla dels 9" per calcular el percentatge de superfície corporal cremada en adults.\n\nRegla del palmell: El palmell de la mà de la víctima (sense el polze) representa aproximadament l\'1% de la seva superfície corporal.',
      'Denne lommeregner bruger "9-reglen" til at beregne procentdelen af forbrændt kropsoverflade hos voksne.\n\nHåndfladeregel: Offerets håndflate (uden tommelfingeren) udgør ca. 1% af kropsoverfladen.'),
    trad(294, 'herramienta.5.selecciona',          'herramienta', 'Selecciona las áreas quemadas', 'Select burned areas', 'Velg brente områder', 'Sélectionnez les zones brûlées', 'Selecciona les àrees cremades', 'Vælg forbrændte områder'),
    trad(295, 'herramienta.5.area.cabeza_cuello',  'herramienta', 'Cabeza y cuello', 'Head and neck', 'Hode og nakke', 'Tête et cou', 'Cap i coll', 'Hoved og hals'),
    trad(296, 'herramienta.5.area.pecho',          'herramienta', 'Pecho (frontal)', 'Chest (front)', 'Bryst (frontal)', 'Poitrine (frontale)', 'Pit (frontal)', 'Bryst (frontal)'),
    trad(297, 'herramienta.5.area.abdomen',        'herramienta', 'Abdomen (frontal)', 'Abdomen (front)', 'Mage (frontal)', 'Abdomen (frontal)', 'Abdomen (frontal)', 'Mave (frontal)'),
    trad(298, 'herramienta.5.area.espalda_superior','herramienta', 'Espalda superior', 'Upper back', 'Øvre rygg', 'Dos supérieur', 'Esquena superior', 'Øvre ryg'),
    trad(299, 'herramienta.5.area.espalda_inferior','herramienta', 'Espalda inferior', 'Lower back', 'Nedre rygg', 'Bas du dos', 'Esquena inferior', 'Nedre ryg'),
    trad(300, 'herramienta.5.area.brazo_der',      'herramienta', 'Brazo derecho', 'Right arm', 'Høyre arm', 'Bras droit', 'Braç dret', 'Højre arm'),
    trad(301, 'herramienta.5.area.brazo_izq',      'herramienta', 'Brazo izquierdo', 'Left arm', 'Venstre arm', 'Bras gauche', 'Braç esquerre', 'Venstre arm'),
    trad(302, 'herramienta.5.area.pierna_der_f',   'herramienta', 'Pierna derecha (frontal)', 'Right leg (front)', 'Høyre bein (frontal)', 'Jambe droite (frontale)', 'Cama dreta (frontal)', 'Højre ben (frontal)'),
    trad(303, 'herramienta.5.area.pierna_der_p',   'herramienta', 'Pierna derecha (posterior)', 'Right leg (back)', 'Høyre bein (bakside)', 'Jambe droite (postérieure)', 'Cama dreta (posterior)', 'Højre ben (bagside)'),
    trad(304, 'herramienta.5.area.pierna_izq_f',   'herramienta', 'Pierna izquierda (frontal)', 'Left leg (front)', 'Venstre bein (frontal)', 'Jambe gauche (frontale)', 'Cama esquerra (frontal)', 'Venstre ben (frontal)'),
    trad(305, 'herramienta.5.area.pierna_izq_p',   'herramienta', 'Pierna izquierda (posterior)', 'Left leg (back)', 'Venstre bein (bakside)', 'Jambe gauche (postérieure)', 'Cama esquerra (posterior)', 'Venstre ben (bagside)'),
    trad(306, 'herramienta.5.area.genitales',      'herramienta', 'Genitales', 'Genitals', 'Kjønnsorgan', 'Organes génitaux', 'Genitals', 'Kønsdele'),
    trad(307, 'herramienta.5.metodo_palma_titulo', 'herramienta', 'Método de la palma', 'Palm method', 'Håndflatermetoden', 'Méthode de la paume', 'Mètode del palmell', 'Håndflademetoden'),
    trad(308, 'herramienta.5.metodo_palma_desc',   'herramienta',
      'Para áreas pequeñas o irregulares, cuenta cuántas veces cabe la palma de la mano de la víctima sobre la quemadura. Cada palma = 1%.',
      'For small or irregular areas, count how many times the victim\'s palm fits over the burn. Each palm = 1%.',
      'For små eller uregelmessige områder, tell hvor mange ganger offerets håndflate passer over forbrenningen. Hver håndflate = 1%.',
      'Pour les petites zones ou irrégulières, comptez combien de fois la paume de la victime couvre la brûlure. Chaque paume = 1%.',
      'Per a àrees petites o irregulars, compta quantes vegades cap el palmell de la mà de la víctima sobre la cremada. Cada palmell = 1%.',
      'For små eller uregelmæssige områder, tæl hvor mange gange offerets håndflate passer over forbrændingen. Hver håndflate = 1%.'),
    trad(309, 'herramienta.5.num_palmas',          'herramienta', 'Número de palmas:', 'Number of palms:', 'Antall håndflater:', 'Nombre de paumes :', 'Nombre de palmells:', 'Antal håndflader:'),
    trad(310, 'herramienta.5.resultado',           'herramienta', 'Resultado', 'Result', 'Resultat', 'Résultat', 'Resultat', 'Resultat'),
    trad(311, 'herramienta.5.severidad',           'herramienta', 'Severidad estimada:', 'Estimated severity:', 'Estimert alvorlighetsgrad:', 'Gravité estimée :', 'Gravetat estimada:', 'Estimeret sværhedsgrad:'),
    trad(312, 'herramienta.5.leve',                'herramienta', 'Leve', 'Mild', 'Mild', 'Légère', 'Lleu', 'Let'),
    trad(313, 'herramienta.5.moderada',            'herramienta', 'Moderada', 'Moderate', 'Moderat', 'Modérée', 'Moderada', 'Moderat'),
    trad(314, 'herramienta.5.grave',               'herramienta', 'Grave', 'Severe', 'Alvorlig', 'Grave', 'Greu', 'Alvorlig'),

    // ── H6 Registro Exploración ────────────────────────────────────────────
    trad(315, 'herramienta.6.aviso',              'herramienta',
      '¿Qué es la exploración secundaria?\nEs una evaluación detallada que se realiza después de asegurarse de que no hay problemas vitales inmediatos. Registra todo lo que observes y lo que la víctima comunique. Esta información es crucial para el personal sanitario.',
      'What is secondary assessment?\nIt is a detailed evaluation performed after ensuring there are no immediate life-threatening problems. Record everything you observe and what the victim communicates. This information is crucial for medical personnel.',
      'Hva er sekundærvurdering?\nDet er en detaljert evaluering som utføres etter å ha sørget for at det ikke er umiddelbare livstruende problemer. Registrer alt du observerer og hva offeret kommuniserer. Denne informasjonen er avgjørende for helsepersonell.',
      'Qu\'est-ce que le bilan secondaire ?\nC\'est une évaluation détaillée effectuée après s\'être assuré qu\'il n\'y a pas de problèmes vitaux immédiats. Enregistrez tout ce que vous observez et ce que la victime communique. Ces informations sont cruciales pour le personnel médical.',
      'Què és l\'exploració secundària?\nÉs una avaluació detallada que es realitza després d\'assegurar-se que no hi ha problemes vitals immediats. Registra tot el que observes i el que la víctima comunica. Aquesta informació és crucial per al personal sanitari.',
      'Hvad er sekundær vurdering?\nDet er en detaljeret evaluering udført efter at sikre, at der ikke er umiddelbare livstruende problemer. Registrer alt du observerer og hvad offeret kommunikerer. Disse oplysninger er afgørende for sundhedspersonalet.'),
    trad(316, 'herramienta.6.selecciona_cat',     'herramienta', 'Selecciona categoría', 'Select category', 'Velg kategori', 'Sélectionnez une catégorie', 'Selecciona categoria', 'Vælg kategori'),
    trad(317, 'herramienta.6.cat.signos_visibles','herramienta', 'Signos visibles', 'Visible signs', 'Synlige tegn', 'Signes visibles', 'Signes visibles', 'Synlige tegn'),
    trad(318, 'herramienta.6.cat.signos_visibles_desc','herramienta', 'Lo que ves (color, textura, hinchazón)', 'What you see (color, texture, swelling)', 'Hva du ser (farge, tekstur, hevelse)', 'Ce que vous voyez (couleur, texture, gonflement)', 'El que veus (color, textura, inflor)', 'Hvad du ser (farve, tekstur, hævelse)'),
    trad(319, 'herramienta.6.cat.sintomas',       'herramienta', 'Síntomas', 'Symptoms', 'Symptomer', 'Symptômes', 'Símptomes', 'Symptomer'),
    trad(320, 'herramienta.6.cat.sintomas_desc',  'herramienta', 'Lo que la víctima describe', 'What the victim describes', 'Hva offeret beskriver', 'Ce que la victime décrit', 'El que la víctima descriu', 'Hvad offeret beskriver'),
    trad(321, 'herramienta.6.cat.signos_vitales', 'herramienta', 'Signos vitales', 'Vital signs', 'Vitale tegn', 'Signes vitaux', 'Signes vitals', 'Vitale tegn'),
    trad(322, 'herramienta.6.cat.signos_vitales_desc','herramienta', 'Pulso, respiración, temperatura', 'Pulse, breathing, temperature', 'Puls, pust, temperatur', 'Pouls, respiration, température', 'Pols, respiració, temperatura', 'Puls, vejrtrækning, temperatur'),
    trad(323, 'herramienta.6.cat.lesiones',       'herramienta', 'Lesiones', 'Injuries', 'Skader', 'Blessures', 'Lesions', 'Skader'),
    trad(324, 'herramienta.6.cat.lesiones_desc',  'herramienta', 'Heridas, fracturas, quemaduras', 'Wounds, fractures, burns', 'Sår, brudd, forbrenninger', 'Plaies, fractures, brûlures', 'Ferides, fractures, cremades', 'Sår, frakturer, forbrændinger'),
    trad(325, 'herramienta.6.cat.historial',      'herramienta', 'Historial médico', 'Medical history', 'Sykehistorie', 'Antécédents médicaux', 'Historial mèdic', 'Sygehistorie'),
    trad(326, 'herramienta.6.cat.historial_desc', 'herramienta', 'Alergias, medicación, enfermedades previas', 'Allergies, medication, previous conditions', 'Allergier, medisiner, tidligere sykdommer', 'Allergies, médicaments, maladies antérieures', 'Al·lèrgies, medicació, malalties prèvies', 'Allergier, medicin, tidligere sygdomme'),
    trad(327, 'herramienta.6.cat.otros',          'herramienta', 'Otros datos', 'Other data', 'Andre data', 'Autres données', 'Altres dades', 'Andre data'),
    trad(328, 'herramienta.6.cat.otros_desc',     'herramienta', 'Información adicional', 'Additional information', 'Tilleggsinformasjon', 'Informations supplémentaires', 'Informació addicional', 'Yderligere oplysninger'),
    trad(329, 'herramienta.6.nueva_obs',          'herramienta', 'Nueva observación', 'New observation', 'Ny observasjon', 'Nouvelle observation', 'Nova observació', 'Ny observation'),
    trad(330, 'herramienta.6.obs_hint',           'herramienta', 'Escribe aquí tu observación...', 'Write your observation here...', 'Skriv din observasjon her...', 'Écrivez votre observation ici...', 'Escriu aquí la teva observació...', 'Skriv din observation her...'),
    trad(331, 'herramienta.6.guardar_obs',        'herramienta', 'Guardar observación', 'Save observation', 'Lagre observasjon', 'Enregistrer l\'observation', 'Desar observació', 'Gem observation'),
    trad(332, 'herramienta.6.sin_obs',            'herramienta',
      'No hay observaciones registradas aún.\nComienza añadiendo información sobre la víctima.',
      'No observations recorded yet.\nStart by adding information about the victim.',
      'Ingen observasjoner registrert ennå.\nStart med å legge til informasjon om offeret.',
      'Aucune observation enregistrée pour le moment.\nCommencez par ajouter des informations sur la victime.',
      'No hi ha observacions registrades encara.\nComença afegint informació sobre la víctima.',
      'Ingen observationer registreret endnu.\nBegynd med at tilføje oplysninger om offeret.'),
    trad(333, 'herramienta.6.obs_registradas',    'herramienta', 'Observaciones registradas:', 'Recorded observations:', 'Registrerte observasjoner:', 'Observations enregistrées :', 'Observacions registrades:', 'Registrerede observationer:'),
    trad(334, 'herramienta.6.ver_resumen',        'herramienta', 'Ver resumen', 'View summary', 'Se sammendrag', 'Voir le résumé', 'Veure resum', 'Se opsummering'),
    trad(335, 'herramienta.6.resumen_titulo',     'herramienta', 'Resumen del registro', 'Record summary', 'Sammendrag av registeret', 'Résumé du registre', 'Resum del registre', 'Registreringsoversigt'),
    trad(336, 'herramienta.6.resumen_copiado',    'herramienta', 'Registro copiado al portapapeles', 'Record copied to clipboard', 'Registeret er kopiert til utklippstavlen', 'Registre copié dans le presse-papiers', 'Registre copiat al porta-retalls', 'Registrering kopieret til udklipsholder'),
    trad(337, 'herramienta.6.copiar',             'herramienta', 'Copiar', 'Copy', 'Kopier', 'Copier', 'Copiar', 'Kopiér'),
    trad(338, 'herramienta.6.cerrar',             'herramienta', 'Cerrar', 'Close', 'Lukk', 'Fermer', 'Tancar', 'Luk'),
    trad(339, 'herramienta.6.borrar_registro',    'herramienta', 'Borrar registro', 'Delete record', 'Slett registeret', 'Supprimer le registre', 'Esborrar registre', 'Slet registrering'),
    trad(340, 'herramienta.6.borrar_confirm',     'herramienta',
      '¿Borrar todas las observaciones? Esta acción no se puede deshacer.',
      'Delete all observations? This action cannot be undone.',
      'Slette alle observasjoner? Denne handlingen kan ikke angres.',
      'Supprimer toutes les observations ? Cette action est irréversible.',
      'Esborrar totes les observacions? Aquesta acció no es pot desfer.',
      'Slet alle observationer? Denne handling kan ikke fortrydes.'),
    trad(341, 'herramienta.6.borrar_todo',        'herramienta', 'Borrar todo', 'Delete all', 'Slett alt', 'Tout supprimer', 'Esborrar tot', 'Slet alt'),

    // ── H7 Ficha Médica ────────────────────────────────────────────────────
    trad(342, 'herramienta.7.aviso_titulo',       'herramienta', 'Información de emergencia', 'Emergency information', 'Nødinformasjon', 'Informations d\'urgence', 'Informació d\'emergència', 'Nødinformation'),
    trad(343, 'herramienta.7.aviso_desc1',        'herramienta',
      'Esta información se guarda en tu dispositivo y puede ser crucial cuando lleguen los servicios de emergencia.',
      'This information is saved on your device and can be crucial when emergency services arrive.',
      'Denne informasjonen lagres på enheten din og kan være avgjørende når nødetatene ankommer.',
      'Ces informations sont enregistrées sur votre appareil et peuvent être cruciales lorsque les services d\'urgence arrivent.',
      'Aquesta informació es guarda al teu dispositiu i pot ser crucial quan arribin els serveis d\'emergència.',
      'Disse oplysninger gemmes på din enhed og kan være afgørende, når nødetaterne ankommer.'),
    trad(344, 'herramienta.7.aviso_desc2',        'herramienta',
      '⚠ Esta aplicación NO es un almacenamiento médico oficial.',
      '⚠ This application is NOT an official medical storage.',
      '⚠ Denne appen er IKKE en offisiell medisinsk lagringsplass.',
      '⚠ Cette application N\'est PAS un stockage médical officiel.',
      '⚠ Aquesta aplicació NO és un emmagatzematge mèdic oficial.',
      '⚠ Denne applikation er IKKE en officiel medicinsk lagring.'),
    trad(345, 'herramienta.7.sec_datos',          'herramienta', 'Datos personales', 'Personal data', 'Personopplysninger', 'Données personnelles', 'Dades personals', 'Personoplysninger'),
    trad(346, 'herramienta.7.campo_nombre',       'herramienta', 'Nombre completo', 'Full name', 'Fullt navn', 'Nom complet', 'Nom complet', 'Fuldt navn'),
    trad(347, 'herramienta.7.campo_grupo',        'herramienta', 'Grupo sanguíneo', 'Blood type', 'Blodtype', 'Groupe sanguin', 'Grup sanguini', 'Blodtype'),
    trad(348, 'herramienta.7.sec_medica',         'herramienta', 'Información médica crítica', 'Critical medical information', 'Kritisk medisinsk informasjon', 'Informations médicales critiques', 'Informació mèdica crítica', 'Kritiske medicinske oplysninger'),
    trad(349, 'herramienta.7.campo_alergias',     'herramienta', 'Alergias', 'Allergies', 'Allergier', 'Allergies', 'Al·lèrgies', 'Allergier'),
    trad(350, 'herramienta.7.campo_medicacion',   'herramienta', 'Medicación habitual', 'Regular medication', 'Fast medisinering', 'Médicaments habituels', 'Medicació habitual', 'Fast medicin'),
    trad(351, 'herramienta.7.campo_enfermedades', 'herramienta', 'Enfermedades / Condiciones médicas', 'Diseases / Medical conditions', 'Sykdommer / Medisinske tilstander', 'Maladies / Conditions médicales', 'Malalties / Condicions mèdiques', 'Sygdomme / Medicinske tilstande'),
    trad(352, 'herramienta.7.campo_tetanos',      'herramienta', 'Última vacuna del tétanos', 'Last tetanus vaccine', 'Siste stivkrampevaksine', 'Dernier vaccin antitétanique', 'Última vacuna del tètanus', 'Seneste stivkrampevaccine'),
    trad(353, 'herramienta.7.campo_donante',      'herramienta', 'Donante de órganos', 'Organ donor', 'Organdonor', 'Donneur d\'organes', 'Donant d\'òrgans', 'Organdonor'),
    trad(354, 'herramienta.7.campo_seguro',       'herramienta', 'Seguro médico / Mutua', 'Health insurance', 'Helseforsikring', 'Assurance maladie', 'Assegurança mèdica', 'Sygeforsikring'),
    trad(355, 'herramienta.7.sec_contactos',      'herramienta', 'Contactos de emergencia', 'Emergency contacts', 'Nødkontakter', 'Contacts d\'urgence', 'Contactes d\'emergència', 'Nødkontakter'),
    trad(356, 'herramienta.7.contacto1',          'herramienta', 'Contacto 1', 'Contact 1', 'Kontakt 1', 'Contact 1', 'Contacte 1', 'Kontakt 1'),
    trad(357, 'herramienta.7.contacto2',          'herramienta', 'Contacto 2', 'Contact 2', 'Kontakt 2', 'Contact 2', 'Contacte 2', 'Kontakt 2'),
    trad(358, 'herramienta.7.campo_nombre_c',     'herramienta', 'Nombre', 'Name', 'Navn', 'Nom', 'Nom', 'Navn'),
    trad(359, 'herramienta.7.campo_tel',          'herramienta', 'Teléfono', 'Phone', 'Telefon', 'Téléphone', 'Telèfon', 'Telefon'),
    trad(360, 'herramienta.7.guardar_ficha',      'herramienta', 'Guardar ficha médica', 'Save medical card', 'Lagre medisinkort', 'Enregistrer la fiche médicale', 'Desar fitxa mèdica', 'Gem medicinkort'),
    trad(361, 'herramienta.7.aviso_privacidad',   'herramienta',
      'ℹ Toda la información se guarda únicamente en tu dispositivo. No se envía a ningún servidor externo.',
      'ℹ All information is stored only on your device. It is not sent to any external server.',
      'ℹ All informasjon lagres kun på enheten din. Den sendes ikke til noen ekstern server.',
      'ℹ Toutes les informations sont stockées uniquement sur votre appareil. Elles ne sont envoyées à aucun serveur externe.',
      'ℹ Tota la informació es guarda únicament al teu dispositiu. No s\'envia a cap servidor extern.',
      'ℹ Alle oplysninger gemmes kun på din enhed. De sendes ikke til nogen ekstern server.'),
    trad(362, 'herramienta.7.guardada',           'herramienta', 'Ficha guardada correctamente', 'Medical card saved successfully', 'Medisinkort lagret', 'Fiche médicale enregistrée avec succès', 'Fitxa mèdica desada correctament', 'Medicinkort gemt'),

    // ── H8 Maniobra Heimlich ───────────────────────────────────────────────
    trad(363, 'herramienta.8.alerta',             'herramienta',
      'Si NO puede hablar, toser con fuerza ni respirar: ACTÚA AHORA.\n\nSi puede toser, anímale a seguir tosiendo por sí mismo.',
      'If they CANNOT speak, cough forcefully or breathe: ACT NOW.\n\nIf they can cough, encourage them to keep coughing on their own.',
      'Hvis de IKKE kan snakke, hoste kraftig eller puste: HANDLE NÅ.\n\nHvis de kan hoste, oppmuntre dem til å fortsette å hoste selv.',
      'S\'ils NE peuvent PAS parler, tousser fort ni respirer : AGISSEZ MAINTENANT.\n\nS\'ils peuvent tousser, encouragez-les à continuer à tousser seuls.',
      'Si NO pot parlar, tossir amb força ni respirar: ACTUA ARA.\n\nSi pot tossir, anima\'l a continuar tossint per si sol.',
      'Hvis de IKKE kan tale, hoste kraftigt eller trække vejret: HANDL NU.\n\nHvis de kan hoste, opfordr dem til at fortsætte med at hoste selv.'),
    trad(364, 'herramienta.8.adulto_titulo',      'herramienta', 'Adulto o niño consciente (>1 año)', 'Conscious adult or child (>1 year)', 'Bevisst voksen eller barn (>1 år)', 'Adulte ou enfant conscient (>1 an)', 'Adult o nen conscient (>1 any)', 'Bevidst voksen eller barn (>1 år)'),
    trad(365, 'herramienta.8.adulto_pasos',       'herramienta',
      'Colócate detrás de la persona y ponla levemente inclinada hacia adelante.\nPon un pie adelante para tener mayor estabilidad.\nCierra un puño y colócalo por encima del ombligo y por debajo del esternón, con el pulgar hacia dentro.\nCon la otra mano, agarra el puño con fuerza.\nRealiza empujes bruscos hacia adentro y hacia arriba.\nRepite hasta que el objeto salga o la persona pierda el conocimiento.',
      'Stand behind the person and tilt them slightly forward.\nPut one foot forward for greater stability.\nMake a fist and place it above the navel and below the sternum, thumb facing inward.\nWith the other hand, grasp the fist firmly.\nPerform quick, sharp thrusts inward and upward.\nRepeat until the object comes out or the person loses consciousness.',
      'Still deg bak personen og lut dem litt fremover.\nSett en fot frem for større stabilitet.\nLag en neve og plasser den over navlen og under brystbenet, med tommelen innover.\nMed den andre hånden, grip neven fast.\nUtfør raske, skarpe støt innover og oppover.\nRepeter til gjenstanden kommer ut eller personen mister bevisstheten.',
      'Placez-vous derrière la personne et inclinez-la légèrement en avant.\nAvancez un pied pour une plus grande stabilité.\nFermez le poing et placez-le au-dessus du nombril et en dessous du sternum, le pouce vers l\'intérieur.\nDe l\'autre main, saisissez le poing fermement.\nEffectuez des poussées brusques vers l\'intérieur et vers le haut.\nRépétez jusqu\'à ce que l\'objet sorte ou que la personne perde connaissance.',
      'Col·loca\'t darrere la persona i inclina-la lleugerament cap endavant.\nPosa un peu endavant per tenir major estabilitat.\nTanca el puny i col·loca\'l per sobre del melic i per sota de l\'estern, amb el polze cap endins.\nAmb l\'altra mà, agafa el puny amb força.\nFes empentes brusques cap endins i cap amunt.\nRepeteix fins que l\'objecte surti o la persona perdi el coneixement.',
      'Stil dig bag personen og vip dem lidt fremad.\nSæt en fod frem for større stabilitet.\nLav en knytnæve og placer den over navlen og under brystbenet, med tommelfingeren indad.\nMed den anden hånd, grib knytnæven fast.\nUdfør hurtige, skarpe støt indad og opad.\nGentagene gange, indtil genstanden kommer ud, eller personen besvimer.'),
    trad(366, 'herramienta.8.bebe_titulo',        'herramienta', 'Bebé (menor de 1 año)', 'Baby (under 1 year)', 'Spedbarn (under 1 år)', 'Bébé (moins d\'1 an)', 'Nadó (menor d\'1 any)', 'Baby (under 1 år)'),
    trad(367, 'herramienta.8.bebe_pasos',         'herramienta',
      'Sujeta al bebé boca abajo sobre tu antebrazo, con la cabeza más baja que el cuerpo.\nDa 5 palmadas firmes entre los omóplatos con el talón de la mano.\nGíralo boca arriba apoyando la cabeza en todo momento.\nDa 5 compresiones torácicas con 2 dedos en el centro del pecho, justo bajo la línea de los pezones.\nAlterna 5 palmadas en la espalda y 5 compresiones en el pecho.\nRepite hasta que el objeto salga o el bebé pierda el conocimiento.',
      'Hold the baby face down on your forearm, with the head lower than the body.\nGive 5 firm back blows between the shoulder blades with the heel of your hand.\nTurn them face up, supporting the head at all times.\nGive 5 chest compressions with 2 fingers in the center of the chest, just below the nipple line.\nAlternate 5 back blows and 5 chest compressions.\nRepeat until the object comes out or the baby loses consciousness.',
      'Hold babyen ansiktet ned på underarmen din, med hodet lavere enn kroppen.\nGi 5 faste slag mellom skulderbladene med håndbaken.\nSnu dem opp ansiktet, støtt hodet hele tiden.\nGi 5 brystkompresjon med 2 fingre midt på brystet, rett under brystvortelinja.\nVeksle 5 slag på ryggen og 5 brystkompresjoner.\nRepeter til gjenstanden kommer ut eller babyen mister bevisstheten.',
      'Tenez le bébé face vers le bas sur votre avant-bras, la tête plus basse que le corps.\nDonnez 5 tapes fermes entre les omoplates avec le talon de la main.\nRetournez-le face vers le haut en soutenant la tête en tout temps.\nDonnez 5 compressions thoraciques avec 2 doigts au centre de la poitrine, juste sous la ligne des mamelons.\nAlternez 5 tapes dans le dos et 5 compressions thoraciques.\nRépétez jusqu\'à ce que l\'objet sorte ou que le bébé perde connaissance.',
      'Aguanta el nadó cara avall sobre el teu avantbraç, amb el cap més baix que el cos.\nDóna 5 palmades fermes entre els omòplats amb el taló de la mà.\nGira\'l cara amunt donant suport al cap en tot moment.\nDóna 5 compressions toràciques amb 2 dits al centre del pit, just per sota de la línia dels mugrons.\nAlterna 5 palmades a l\'esquena i 5 compressions al pit.\nRepeteix fins que l\'objecte surti o el nadó perdi el coneixement.',
      'Hold babyen ansigt nedad på din underarm, med hovedet lavere end kroppen.\nGiv 5 faste klap mellem skulderbladene med håndroden.\nVend dem ansigt opad, støt hovedet hele tiden.\nGiv 5 brystkompressioner med 2 fingre midt på brystet, lige under brystvortelinjen.\nSkift mellem 5 slag på ryggen og 5 brystkompressioner.\nGentagene gange, indtil genstanden kommer ud, eller babyen besvimer.'),
    trad(368, 'herramienta.8.bebe_advertencia',   'herramienta',
      'NO hagas compresiones abdominales (Heimlich) en bebés menores de 1 año.',
      'DO NOT perform abdominal compressions (Heimlich) on babies under 1 year old.',
      'IKKE gjør magekompresjoner (Heimlich) på spedbarn under 1 år.',
      'NE FAITES PAS de compressions abdominales (Heimlich) sur les bébés de moins de 1 an.',
      'NO facis compressions abdominals (Heimlich) en nadons menors d\'1 any.',
      'LAV IKKE mavekompressioner (Heimlich) på babyer under 1 år.'),
    trad(369, 'herramienta.8.inconsciente_titulo','herramienta', 'Si pierde el conocimiento', 'If unconscious', 'Hvis bevisstløs', 'En cas de perte de connaissance', 'Si perd el coneixement', 'Hvis bevidstløs'),
    trad(370, 'herramienta.8.inconsciente_pasos', 'herramienta',
      'Llama al 112 inmediatamente.\nTúmbala en el suelo con cuidado boca arriba.\nInicia la RCP: 30 compresiones torácicas + 2 ventilaciones.\nAntes de cada ventilación, mira en la boca y extrae el objeto solo si lo ves claramente.\nContinúa hasta que llegue la ayuda o la persona recupere el conocimiento.',
      'Call 112 immediately.\nLay them carefully on the floor face up.\nBegin CPR: 30 chest compressions + 2 breaths.\nBefore each breath, look in the mouth and remove the object only if you can clearly see it.\nContinue until help arrives or the person regains consciousness.',
      'Ring 112 umiddelbart.\nLegg dem forsiktig på gulvet med ansiktet opp.\nStart HLR: 30 brystkompresjoner + 2 innblåsinger.\nFør hver innblåsing, se i munnen og fjern gjenstanden bare hvis du tydelig ser den.\nFortsett til hjelp ankommer eller personen gjenvinner bevisstheten.',
      'Appelez le 112 immédiatement.\nAllongez-les délicatement au sol sur le dos.\nCommencez la RCP : 30 compressions thoraciques + 2 ventilations.\nAvant chaque ventilation, regardez dans la bouche et retirez l\'objet seulement si vous le voyez clairement.\nContinuez jusqu\'à l\'arrivée des secours ou la reprise de connaissance.',
      'Truca al 112 immediatament.\nTomba\'l amb cura al terra boca amunt.\nInicia la RCP: 30 compressions toràciques + 2 ventilacions.\nAbans de cada ventilació, mira a la boca i extreu l\'objecte només si el veus clarament.\nContinua fins que arribi l\'ajuda o la persona recuperi el coneixement.',
      'Ring 112 øjeblikkeligt.\nLæg dem forsigtigt på gulvet med ansigtet opad.\nPåbegynd HLR: 30 brystkompressioner + 2 indblæsninger.\nFør hver indblæsning, kig i munden og fjern genstanden kun hvis du tydeligt kan se den.\nFortsæt, indtil hjælp ankommer eller personen genvinder bevidstheden.'),
    trad(371, 'herramienta.8.auto_titulo',        'herramienta', 'Si estás solo/a (automaniobra)', 'If alone (self-maneuver)', 'Hvis du er alene (selvmanøver)', 'Si vous êtes seul(e) (auto-manœuvre)', "Si estàs sol/a (automaniobra)", 'Hvis du er alene (selvmanøvre)'),
    trad(372, 'herramienta.8.auto_pasos',         'herramienta',
      'Cierra un puño por encima del ombligo y empuja con fuerza hacia adentro y hacia arriba.\nO inclínate sobre el respaldo de una silla o el borde de una mesa y ejerce presión brusca sobre el abdomen.\nRepite con fuerza hasta que el objeto salga.',
      'Make a fist above the navel and thrust forcefully inward and upward.\nOr lean over the back of a chair or the edge of a table and apply sharp pressure to the abdomen.\nRepeat forcefully until the object comes out.',
      'Lag en neve over navlen og trykk kraftig innover og oppover.\nEller lut deg over ryggen på en stol eller kanten av et bord og utøv skarp trykk mot magen.\nRepeter kraftig til gjenstanden kommer ut.',
      'Fermez le poing au-dessus du nombril et poussez avec force vers l\'intérieur et vers le haut.\nOu penchez-vous sur le dossier d\'une chaise ou le bord d\'une table et exercez une pression brusque sur l\'abdomen.\nRépétez avec force jusqu\'à ce que l\'objet sorte.',
      'Tanca el puny per sobre del melic i empeny amb força cap endins i cap amunt.\nO inclina\'t sobre el respatller d\'una cadira o la vora d\'una taula i exerceix pressió sobtada sobre l\'abdomen.\nRepeteix amb força fins que l\'objecte surti.',
      'Lav en knytnæve over navlen og tryk kraftigt indad og opad.\nEller læn dig over ryggen på en stol eller kanten af et bord og udøv et skarpt tryk på maven.\nGentag kraftigt, indtil genstanden kommer ud.'),

    // ── H9 Guía Quemaduras ─────────────────────────────────────────────────
    trad(373, 'herramienta.9.aviso',              'herramienta',
      'Ante cualquier quemadura, lo primero es alejar a la persona de la fuente de calor y eliminar la causa (apagar llamas, retirar ropa no pegada, limpiar producto químico).',
      'For any burn, the first step is to move the person away from the heat source and eliminate the cause (extinguish flames, remove non-stuck clothing, rinse off chemicals).',
      'Ved enhver forbrenning er det første å flytte personen bort fra varmekilden og eliminere årsaken (slukke flammer, fjerne klær som ikke sitter fast, skylle av kjemikalier).',
      'Pour toute brûlure, la première étape est d\'éloigner la personne de la source de chaleur et d\'éliminer la cause (éteindre les flammes, retirer les vêtements non collés, rincer les produits chimiques).',
      'Davant qualsevol cremada, el primer és allunyar la persona de la font de calor i eliminar la causa (apagar flames, treure roba no enganxada, netejar producte químic).',
      'Ved enhver forbrænding er det første at flytte personen væk fra varmekilden og fjerne årsagen (slukke flammer, fjerne ikke-fastsiddende tøj, skylle kemikalier af).'),
    trad(374, 'herramienta.9.identifica',         'herramienta', 'Identifica el grado', 'Identify the degree', 'Identifiser graden', 'Identifiez le degré', 'Identifica el grau', 'Identificér graden'),
    trad(375, 'herramienta.9.grado1_titulo',      'herramienta', '1.er grado — Superficial', '1st degree — Superficial', '1. grad — Overfladisk', '1er degré — Superficiel', '1r grau — Superficial', '1. grad — Overfladisk'),
    trad(376, 'herramienta.9.grado1_sintomas',    'herramienta',
      'Piel enrojecida, seca y dolorosa\nSin ampollas\nSolo afecta la capa superficial de la piel\nEjemplo: quemadura solar leve, contacto breve con objeto caliente',
      'Red, dry and painful skin\nNo blisters\nOnly affects the superficial skin layer\nExample: mild sunburn, brief contact with a hot object',
      'Rød, tørr og smertefull hud\nIngen blemmer\nPåvirker kun det overfladiske hudlaget\nEksempel: lett solforbrenning, kort kontakt med varm gjenstand',
      'Peau rouge, sèche et douloureuse\nPas d\'ampoules\nN\'affecte que la couche superficielle de la peau\nExemple : coup de soleil léger, contact bref avec un objet chaud',
      'Pell vermella, seca i dolorosa\nSense butllofes\nNomés afecta la capa superficial de la pell\nExemple: cremada solar lleu, contacte breu amb objecte calent',
      'Rød, tør og smertefuld hud\nIngen blærer\nPåvirker kun det overfladiske hudlag\nEksempel: let solskoldning, kort kontakt med en varm genstand'),
    trad(377, 'herramienta.9.grado1_tratamiento', 'herramienta',
      'Aplica agua fría corriente durante 10–20 minutos\nNo uses hielo, mantequilla ni cremas\nCubre con tela limpia y no adherente\nToma un analgésico si el dolor es intenso\nBusca atención médica si la zona es grande o no mejora en 5 días',
      'Apply cool running water for 10–20 minutes\nDo not use ice, butter or creams\nCover with clean, non-adherent cloth\nTake a painkiller if pain is severe\nSeek medical attention if the area is large or does not improve in 5 days',
      'Påfør kjølig rennende vann i 10–20 minutter\nIkke bruk is, smør eller kremer\nDekk til med rent, ikke-klebende stoff\nTa et smertestillende middel hvis smerten er intens\nOppsøk legehjelp hvis området er stort eller ikke bedres i løpet av 5 dager',
      'Appliquez de l\'eau froide courante pendant 10–20 minutes\nN\'utilisez pas de glace, de beurre ni de crèmes\nCouvrez avec un tissu propre et non adhérent\nPrenez un analgésique si la douleur est intense\nConsultez un médecin si la zone est grande ou ne s\'améliore pas en 5 jours',
      'Aplica aigua freda corrent durant 10–20 minuts\nNo facis servir gel, mantequilla ni cremes\nCobreix amb tela neta i no adherent\nPrén un analgèsic si el dolor és intens\nBusca atenció mèdica si la zona és gran o no millora en 5 dies',
      'Påfør køligt rindende vand i 10–20 minutter\nBrug ikke is, smør eller cremer\nDæk til med rent, ikke-klæbende stof\nTag et smertestillende middel, hvis smerten er intens\nSøg lægehjælp, hvis området er stort, eller det ikke bedres inden for 5 dage'),
    trad(378, 'herramienta.9.grado2_titulo',      'herramienta', '2.º grado — Parcial', '2nd degree — Partial', '2. grad — Delvis', '2e degré — Partiel', '2n grau — Parcial', '2. grad — Delvis'),
    trad(379, 'herramienta.9.grado2_sintomas',    'herramienta',
      'Piel enrojecida, húmeda y con ampollas\nDolor muy intenso\nAfecta la epidermis y parte de la dermis\nPosible hinchazón',
      'Red, moist skin with blisters\nVery intense pain\nAffects epidermis and part of the dermis\nPossible swelling',
      'Rød, fuktig hud med blemmer\nSvært intens smerte\nPåvirker overhuden og deler av underhuden\nMulig hevelse',
      'Peau rouge, humide et avec des ampoules\nDouleur très intense\nAffecte l\'épiderme et une partie du derme\nGonflement possible',
      'Pell vermella, humida i amb butllofes\nDolor molt intens\nAfecta l\'epidermis i part de la dermis\nPossible inflor',
      'Rød, fugtig hud med blærer\nMeget intens smerte\nPåvirker overhuden og dele af læderhuden\nMulig hævelse'),
    trad(380, 'herramienta.9.grado2_tratamiento', 'herramienta',
      'Aplica agua fría corriente durante 15–20 minutos\nNO revientes las ampollas (protegen contra infección)\nCubre con gasa estéril húmeda sin apretar\nRetira ropa y joyas si no están pegadas a la piel\nAcude a urgencias o llama al 112 si es una zona grande o sensible',
      'Apply cool running water for 15–20 minutes\nDO NOT burst the blisters (they protect against infection)\nCover loosely with moist sterile gauze\nRemove clothing and jewellery if not stuck to skin\nGo to the emergency room or call 112 if it is a large or sensitive area',
      'Påfør kjølig rennende vann i 15–20 minutter\nIKKE spreng blemmene (de beskytter mot infeksjon)\nDekk løst med fuktig steril gasbind\nFjern klær og smykker hvis de ikke sitter fast i huden\nOppsøk legevakten eller ring 112 hvis det er et stort eller sensitivt område',
      'Appliquez de l\'eau froide courante pendant 15–20 minutes\nNE crevez PAS les ampoules (elles protègent contre l\'infection)\nCouvrez sans serrer avec une gaze stérile humide\nRetirez vêtements et bijoux s\'ils ne collent pas à la peau\nRendez-vous aux urgences ou appelez le 112 si la zone est grande ou sensible',
      'Aplica aigua freda corrent durant 15–20 minuts\nNO rebentis les butllofes (protegeixen contra la infecció)\nCobreix amb gasa estèril humida sense apretar\nRetira roba i joies si no estan enganxades a la pell\nAcudeix a urgències o truca al 112 si és una zona gran o sensible',
      'Påfør køligt rindende vand i 15–20 minutter\nSPRING IKKE blærerne (de beskytter mod infektion)\nDæk løst med fugtigt sterilt gazebind\nFjern tøj og smykker, hvis de ikke sidder fast i huden\nTag på skadestuen eller ring 112, hvis det er et stort eller sensitivt område'),
    trad(381, 'herramienta.9.grado3_titulo',      'herramienta', '3.er grado — Profundo', '3rd degree — Deep', '3. grad — Dyp', '3e degré — Profond', '3r grau — Profund', '3. grad — Dyb'),
    trad(382, 'herramienta.9.grado3_sintomas',    'herramienta',
      'Piel blanquecina, marrón, negra o carbonizada\nAspecto seco, coriáceo o apergaminado\nPoco o ningún dolor — los nervios están destruidos (¡engañoso!)\nAfecta todas las capas de la piel',
      'Whitish, brown, black or charred skin\nDry, leathery or parchment-like appearance\nLittle or no pain — nerves are destroyed (deceptive!)\nAffects all layers of the skin',
      'Hvitaktig, brun, svart eller forkullet hud\nTørt, læraktig eller pergamentaktig utseende\nLite eller ingen smerte — nervene er ødelagte (villedende!)\nPåvirker alle hudlag',
      'Peau blanchâtre, brune, noire ou carbonisée\nAspect sec, coriace ou parcheminé\nPeu ou pas de douleur — les nerfs sont détruits (trompeur !)\nAffecte toutes les couches de la peau',
      'Pell blanquinosa, marró, negra o carbonitzada\nAspecte sec, coriaci o apergaminat\nPoc o cap dolor — els nervis estan destruïts (enganyós!)\nAfecta totes les capes de la pell',
      'Hvidlig, brun, sort eller forkullede hud\nTørt, læderagtigt eller pergamentagtigt udseende\nLidt eller ingen smerte — nerverne er ødelagt (vildledende!)\nPåvirker alle hudlag'),
    trad(383, 'herramienta.9.grado3_tratamiento', 'herramienta',
      'Llama al 112 INMEDIATAMENTE\nNo retires ropa o materiales pegados a la piel\nCubre con tela limpia y seca\nNo apliques agua si la quemadura es muy extensa\nMantén a la persona caliente y tranquila hasta que llegue la ayuda',
      'Call 112 IMMEDIATELY\nDo not remove clothing or materials stuck to skin\nCover with clean, dry cloth\nDo not apply water if the burn is very extensive\nKeep the person warm and calm until help arrives',
      'Ring 112 UMIDDELBART\nIkke fjern klær eller materialer som sitter fast i huden\nDekk til med rent, tørt stoff\nIkke påfør vann hvis forbrenningen er svært omfattende\nHold personen varm og rolig til hjelp ankommer',
      'Appelez le 112 IMMÉDIATEMENT\nNe retirez pas les vêtements ou matériaux collés à la peau\nCouvrez avec un tissu propre et sec\nN\'appliquez pas d\'eau si la brûlure est très étendue\nGardez la personne au chaud et au calme jusqu\'à l\'arrivée des secours',
      'Truca al 112 IMMEDIATAMENT\nNo retires roba o materials enganxats a la pell\nCobreix amb tela neta i seca\nNo apliquis aigua si la cremada és molt extensa\nMantén la persona calenta i tranquil·la fins que arribi l\'ajuda',
      'Ring 112 ØJEBLIKKELIGT\nFjern ikke tøj eller materialer, der sidder fast i huden\nDæk til med rent, tørt stof\nPåfør ikke vand, hvis forbrændingen er meget udbredt\nHold personen varm og rolig, indtil hjælp ankommer'),
    trad(384, 'herramienta.9.grado3_grave',       'herramienta', 'GRAVE', 'SEVERE', 'ALVORLIG', 'GRAVE', 'GREU', 'ALVORLIG'),
    trad(385, 'herramienta.9.como_identificar',   'herramienta', 'Cómo identificarlo', 'How to identify it', 'Slik identifiserer du det', 'Comment l\'identifier', 'Com identificar-lo', 'Sådan identificeres det'),
    trad(386, 'herramienta.9.que_hacer',          'herramienta', 'Qué hacer', 'What to do', 'Hva du skal gjøre', 'Que faire', 'Què fer', 'Hvad man skal gøre'),
    trad(387, 'herramienta.9.no_hagas',           'herramienta', 'NO hagas esto', 'Do NOT do this', 'IKKE gjør dette', 'NE faites PAS ceci', 'NO facis això', 'GØR IKKE dette'),
    trad(388, 'herramienta.9.no_hagas_items',     'herramienta',
      'Aplicar hielo directamente (provoca crioquemadura sobre la herida)\nUsar mantequilla, aceite o pasta de dientes (atrapan calor y favorecen infección)\nReventar ampollas (son barrera natural contra la infección)\nArrancar ropa o materiales pegados a la piel\nCubrir con algodón o materiales que se adhieran',
      'Apply ice directly (causes frostbite on the wound)\nUse butter, oil or toothpaste (trap heat and promote infection)\nBurst blisters (natural barrier against infection)\nTear off clothing or materials stuck to skin\nCover with cotton or adhesive materials',
      'Påfør is direkte (forårsaker frostskade på såret)\nBruk smør, olje eller tannkrem (fanger varme og fremmer infeksjon)\nSpreng blemmer (naturlig barriere mot infeksjon)\nRiv av klær eller materialer som sitter fast i huden\nDekk til med bomull eller klebende materialer',
      'Appliquer de la glace directement (provoque des gelures sur la plaie)\nUtiliser du beurre, de l\'huile ou du dentifrice (emprisonnent la chaleur et favorisent l\'infection)\nCrever les ampoules (barrière naturelle contre l\'infection)\nArracher les vêtements ou matériaux collés à la peau\nCouvrir avec du coton ou des matériaux adhérents',
      'Aplicar gel directament (provoca crioquemadura sobre la ferida)\nFer servir mantequilla, oli o pasta de dents (atrapen calor i afavoreixen infecció)\nRebentar butllofes (barriera natural contra la infecció)\nArrencar roba o materials enganxats a la pell\nCobreix amb cotó o materials que s\'enganxin',
      'Påfør is direkte (forårsager frostskade på såret)\nBrug smør, olie eller tandpasta (fanger varme og fremmer infektion)\nSpring blærer (naturlig barriere mod infektion)\nRiv tøj eller materialer af, der sidder fast i huden\nDæk til med bomuld eller klæbende materialer'),
    trad(389, 'herramienta.9.llama_112',          'herramienta', 'Llama al 112 si...', 'Call 112 if...', 'Ring 112 hvis...', 'Appelez le 112 si...', 'Truca al 112 si...', 'Ring 112 hvis...'),
    trad(390, 'herramienta.9.llama_112_items',    'herramienta',
      'Cualquier quemadura de 3.er grado\nQuemadura en cara, manos, pies, genitales o articulaciones\nQuemadura circular (rodea un miembro)\nQuemadura química o eléctrica\nSuperficie >10% en adultos o >5% en niños (2.º grado)\nSignos de inhalación: voz ronca, tos, cejas quemadas',
      'Any 3rd-degree burn\nBurn on face, hands, feet, genitals or joints\nCircumferential burn (surrounds a limb)\nChemical or electrical burn\nArea >10% in adults or >5% in children (2nd degree)\nInhalation signs: hoarse voice, cough, singed eyebrows',
      'Enhver 3. grads forbrenning\nForbrenning i ansikt, hender, føtter, kjønnsorgan eller ledd\nSirkulær forbrenning (omgir et lem)\nKjemisk eller elektrisk forbrenning\nOmråde >10% hos voksne eller >5% hos barn (2. grad)\nInhalasjonssymptomer: hes stemme, hoste, svedde øyenbryn',
      'Toute brûlure du 3e degré\nBrûlure sur le visage, les mains, les pieds, les organes génitaux ou les articulations\nBrûlure circulaire (entourant un membre)\nBrûlure chimique ou électrique\nSuperficie >10% chez l\'adulte ou >5% chez l\'enfant (2e degré)\nSigles d\'inhalation : voix rauque, toux, sourcils brûlés',
      'Qualsevol cremada de 3r grau\nCremada a la cara, mans, peus, genitals o articulacions\nCremada circular (envolta un membre)\nCremada química o elèctrica\nSuperfície >10% en adults o >5% en nens (2n grau)\nSigles d\'inhalació: veu ronca, tos, celles cremades',
      'Enhver 3. grads forbrænding\nForbrænding på ansigt, hænder, fødder, kønsdele eller led\nCirkulær forbrænding (omslutter et lem)\nKemisk eller elektrisk forbrænding\nAreal >10% hos voksne eller >5% hos børn (2. grad)\nInhalationssymptomer: hæs stemme, hoste, svedne øjenbryn'),
  ]);

  console.log('✅ 174 claves (217-390) de pantallas de herramientas añadidas/actualizadas en Firestore.');
  process.exit(0);
}

migrate().catch((err) => {
  console.error('❌ Error:', err);
  process.exit(1);
});
