require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const { db } = require('../config/firebase');

async function migrate() {
  console.log('Actualizando claves 1-192 con todos los idiomas (es/en/no/fr/ca/da)...');

  const trad = (id, nombre, contexto, esText, enText, noText, frText, caText, daText) =>
    db.collection('traducciones').doc(String(id)).set(
      {
        id_texto: id,
        nombre_texto: nombre,
        contexto,
        version: '1.0.0',
        traducciones: { es: esText, en: enText, no: noText, fr: frText, ca: caText, da: daText },
      },
      { merge: true },
    );

  // emergencias (1-30)
  await Promise.all([
    trad(1, 'emergencia.1.titulo', 'emergencia',
      'Entorno NO Seguro', 'Unsafe Environment',
      'Utrygt Miljø', 'Environnement NON Sécurisé', 'Entorn NO Segur', 'USIKKERT Miljø'),
    trad(2, 'emergencia.1.descripcion', 'emergencia',
      'NO es seguro. Alerta al 112 y espera a que la zona sea segura.',
      'NOT safe. Alert 112 and wait until the area is safe.',
      'IKKE sikkert. Varsle 112 og vent til området er sikkert.',
      'PAS sécurisé. Alertez le 112 et attendez que la zone soit sécurisée.',
      'NO és segur. Avisa el 112 i espera que la zona sigui segura.',
      'IKKE sikkert. Alarmér 112 og vent, til området er sikkert.'),
    trad(3, 'emergencia.1.informacion', 'emergencia',
      'Tipo de peligro presente (fuego, tráfico, cables eléctricos, etc.)\nUbicación exacta del peligro\nSi hay personas en peligro y cuántas',
      'Type of hazard present (fire, traffic, electrical cables, etc.)\nExact location of the hazard\nWhether there are people in danger and how many',
      'Type fare til stede (brann, trafikk, elektriske kabler, etc.)\nNøyaktig plassering av faren\nOm det er personer i fare og hvor mange',
      'Type de danger présent (feu, trafic, câbles électriques, etc.)\nLocalisation exacte du danger\nS\'il y a des personnes en danger et combien',
      'Tipus de perill present (foc, trànsit, cables elèctrics, etc.)\nUbicació exacta del perill\nSi hi ha persones en perill i quantes',
      'Type fare til stede (brand, trafik, el-kabler, osv.)\nNøjagtig placering af faren\nOm der er personer i fare og hvor mange'),
    trad(4, 'emergencia.2.titulo', 'emergencia',
      'Otra Emergencia', 'Other Emergency',
      'Annen Nødsituasjon', 'Autre Urgence', 'Altra Emergència', 'Anden Nødsituation'),
    trad(5, 'emergencia.2.descripcion', 'emergencia',
      'Llama al 112 para orientación profesional.', 'Call 112 for professional guidance.',
      'Ring 112 for profesjonell veiledning.', 'Appelez le 112 pour des conseils professionnels.',
      'Truca al 112 per a orientació professional.', 'Ring 112 for professionel vejledning.'),
    trad(6, 'emergencia.2.informacion', 'emergencia',
      'Describe los síntomas o lesiones detectadas con detalle\nAntecedentes médicos relevantes (alergias, medicamentos, enfermedades)',
      'Describe the detected symptoms or injuries in detail\nRelevant medical history (allergies, medications, conditions)',
      'Beskriv symptomene eller skadene som er oppdaget i detalj\nRelevant medisinsk historikk (allergier, medisiner, sykdommer)',
      'Décrivez en détail les symptômes ou blessures détectés\nAntécédents médicaux pertinents (allergies, médicaments, maladies)',
      'Descriu els símptomes o lesions detectades amb detall\nAntecedents mèdics rellevants (al·lèrgies, medicaments, malalties)',
      'Beskriv detaljeret de opdagede symptomer eller skader\nRelevant sygehistorie (allergier, medicin, sygdomme)'),
    trad(7, 'emergencia.3.titulo', 'emergencia',
      'Posible Hipoglucemia', 'Possible Hypoglycemia',
      'Mulig Hypoglykemi', 'Possible Hypoglycémie', 'Possible Hipoglucèmia', 'Mulig Hypoglykæmi'),
    trad(8, 'emergencia.3.descripcion', 'emergencia',
      'Si está consciente, dale azúcar. Llama al 112 si no mejora.',
      'If conscious, give sugar. Call 112 if no improvement.',
      'Hvis bevisst, gi sukker. Ring 112 hvis ingen bedring.',
      'Si conscient, donnez du sucre. Appelez le 112 si aucune amélioration.',
      'Si està conscient, dona-li sucre. Truca al 112 si no millora.',
      'Hvis bevidst, giv sukker. Ring 112, hvis ingen bedring.'),
    trad(9, 'emergencia.3.informacion', 'emergencia',
      'La persona es diabética\nPresenta sudor frío, temblores, confusión o debilidad\nSi está consciente y se le ha dado azúcar o zumo',
      'The person is diabetic\nPresents cold sweat, tremors, confusion or weakness\nIf conscious and has been given sugar or juice',
      'Personen er diabetiker\nHar kaldsvette, skjelvinger, forvirring eller svakhet\nHvis bevisst og fått sukker eller juice',
      'La personne est diabétique\nPrésente sueurs froides, tremblements, confusion ou faiblesse\nSi consciente et on lui a donné du sucre ou du jus',
      'La persona és diabètica\nPresenta suor freda, tremolors, confusió o debilitat\nSi està conscient i se li ha donat sucre o suc',
      'Personen er diabetiker\nHar koldsved, rysteture, forvirring eller svaghed\nHvis bevidst og har fået sukker eller juice'),
    trad(10, 'emergencia.4.titulo', 'emergencia',
      'Hemorragia Severa', 'Severe Bleeding',
      'Alvorlig Blødning', 'Hémorragie Sévère', 'Hemorràgia Severa', 'Svær Blødning'),
    trad(11, 'emergencia.4.descripcion', 'emergencia',
      'Aplica compresión directa inmediatamente y llama al 112.',
      'Apply direct pressure immediately and call 112.',
      'Påfør direkte trykk umiddelbart og ring 112.',
      'Appliquez une pression directe immédiatement et appelez le 112.',
      'Aplica compressió directa immediatament i truca al 112.',
      'Påfør direkte tryk omgående og ring 112.'),
    trad(12, 'emergencia.4.informacion', 'emergencia',
      'Localización exacta de la hemorragia\nIntensidad del sangrado (abundante, a borbotones)\nSi has aplicado compresión directa sobre la herida\nSi la persona muestra signos de shock (palidez, sudor frío, temblores)',
      'Exact location of the bleeding\nIntensity of bleeding (heavy, spurting)\nIf you have applied direct pressure on the wound\nIf the person shows signs of shock (paleness, cold sweat, tremors)',
      'Nøyaktig plassering av blødningen\nBlødningsintensitet (kraftig, pumping)\nOm du har påført direkte trykk på såret\nOm personen viser tegn på sjokk (blekhet, kaldsvette, skjelvinger)',
      'Localisation exacte de l\'hémorragie\nIntensité du saignement (abondant, en jets)\nSi vous avez appliqué une pression directe sur la blessure\nSi la personne montre des signes de choc (pâleur, sueurs froides, tremblements)',
      'Localització exacta de l\'hemorràgia\nIntensitat del sagnat (abundant, a rajolades)\nSi has aplicat compressió directa sobre la ferida\nSi la persona mostra signes de xoc (pal·lidesa, suor freda, tremolors)',
      'Nøjagtig placering af blødningen\nBlødningens intensitet (kraftig, pumper)\nOm du har påført direkte tryk på såret\nOm personen viser tegn på shock (bleghed, koldsved, rysteture)'),
    trad(13, 'emergencia.5.titulo', 'emergencia',
      'Posible Ictus / AVC', 'Possible Stroke / CVA',
      'Mulig Slag / Hjerneslag', 'Possible AVC / Accident Vasculaire Cérébral',
      'Possible Ictus / AVC', 'Muligt Slagtilfælde / Apopleksi'),
    trad(14, 'emergencia.5.descripcion', 'emergencia',
      'El tiempo es crítico. Llama al 112 inmediatamente.',
      'Time is critical. Call 112 immediately.',
      'Tid er avgjørende. Ring 112 umiddelbart.',
      'Le temps est critique. Appelez le 112 immédiatement.',
      'El temps és crític. Truca al 112 immediatament.',
      'Tid er afgørende. Ring 112 straks.'),
    trad(15, 'emergencia.5.informacion', 'emergencia',
      'Debilidad o caída de un lado de la cara\nDesde cuándo comenzaron los síntomas (CRÍTICO)\nSi hay dificultad para hablar o entender\nSi hay debilidad en brazo o pierna',
      'Weakness or drooping on one side of the face\nWhen symptoms started (CRITICAL)\nIf there is difficulty speaking or understanding\nIf there is weakness in arm or leg',
      'Svakhet eller henging på den ene siden av ansiktet\nNår symptomene begynte (KRITISK)\nOm det er vanskeligheter med å snakke eller forstå\nOm det er svakhet i arm eller bein',
      'Faiblesse ou affaissement d\'un côté du visage\nDepuis quand les symptômes ont commencé (CRITIQUE)\nS\'il y a des difficultés à parler ou à comprendre\nS\'il y a une faiblesse dans le bras ou la jambe',
      'Debilitat o caiguda d\'un costat de la cara\nDes de quan van començar els símptomes (CRÍTIC)\nSi hi ha dificultat per parlar o entendre\nSi hi ha debilitat al braç o a la cama',
      'Svaghed eller hængende på den ene side af ansigtet\nHvornår symptomerne startede (KRITISK)\nOm der er vanskeligheder med at tale eller forstå\nOm der er svaghed i arm eller ben'),
    trad(16, 'emergencia.6.titulo', 'emergencia',
      'Posible Infarto', 'Possible Heart Attack',
      'Mulig Hjerteinfarkt', 'Possible Crise Cardiaque', 'Possible Infart', 'Muligt Hjerteanfald'),
    trad(17, 'emergencia.6.descripcion', 'emergencia',
      'Llama al 112 y mantén a la persona en reposo.',
      'Call 112 and keep the person at rest.',
      'Ring 112 og hold personen i ro.',
      'Appelez le 112 et gardez la personne au repos.',
      'Truca al 112 i mantén la persona en repòs.',
      'Ring 112 og hold personen i ro.'),
    trad(18, 'emergencia.6.informacion', 'emergencia',
      'Dolor intenso en el pecho, opresión o fuerte presión\nDesde cuándo lleva el dolor\nSi el dolor irradia hacia brazo, cuello o mandíbula\nSi hay sudor frío, náuseas o dificultad respiratoria',
      'Intense chest pain, tightness or strong pressure\nHow long the pain has lasted\nIf the pain radiates to the arm, neck or jaw\nIf there is cold sweat, nausea or breathing difficulty',
      'Intense brystsmerter, trykk eller sterk press\nHvor lenge smertene har vart\nOm smertene stråler til arm, nakke eller kjeve\nOm det er kaldsvette, kvalme eller pustevansker',
      'Douleur intense dans la poitrine, oppression ou forte pression\nDepuis combien de temps la douleur dure\nSi la douleur irradie vers le bras, le cou ou la mâchoire\nS\'il y a des sueurs froides, nausées ou difficultés respiratoires',
      'Dolor intens al pit, opressió o forta pressió\nDes de quan dura el dolor\nSi el dolor irradia cap al braç, coll o mandíbula\nSi hi ha suor freda, nàusees o dificultat respiratòria',
      'Intense brystsmerter, trykken eller stærkt pres\nHvor længe smerten har varet\nOm smerten stråler ud i arm, nakke eller kæbe\nOm der er koldsved, kvalme eller åndedrætsbesvær'),
    trad(19, 'emergencia.7.titulo', 'emergencia',
      'Atragantamiento', 'Choking',
      'Kvelning', 'Étouffement', 'Ofegament', 'Kvælning'),
    trad(20, 'emergencia.7.descripcion', 'emergencia',
      'Aplica palmadas en la espalda y compresiones abdominales.',
      'Apply back blows and abdominal compressions.',
      'Gi ryggslag og magetrykk.',
      'Appliquez des claques dans le dos et des compressions abdominales.',
      'Aplica cops a l\'esquena i compressions abdominals.',
      'Giv rygslag og mavekompressioner.'),
    trad(21, 'emergencia.7.informacion', 'emergencia',
      'La persona está atragantada (incapaz de hablar)\nSi puede toser o hablar (atragantamiento parcial vs total)\nSi ya ha iniciado maniobras de Heimlich\nSi presenta coloración azulada (cianosis)',
      'The person is choking (unable to speak)\nIf they can cough or speak (partial vs total obstruction)\nIf Heimlich maneuver has already been initiated\nIf there is bluish coloration (cyanosis)',
      'Personen er kvelnet (ute av stand til å snakke)\nOm han/hun kan hoste eller snakke (delvis vs total tilstopping)\nOm Heimlich-manøveren allerede er igangsatt\nOm det er blåfarge (cyanose)',
      'La personne s\'étouffe (incapable de parler)\nSi elle peut tousser ou parler (obstruction partielle vs totale)\nSi la manœuvre de Heimlich a déjà été initiée\nSi elle présente une coloration bleutée (cyanose)',
      'La persona s\'ofega (incapaç de parlar)\nSi pot tossir o parlar (ofegament parcial vs total)\nSi ja s\'han iniciat maniobres de Heimlich\nSi presenta coloració blavosa (cianosi)',
      'Personen kvæler sig (ude af stand til at tale)\nOm vedkommende kan hoste eller tale (delvis vs total tilstopning)\nOm Heimlich-manøvren allerede er iværksat\nOm der er blålig misfarvning (cyanose)'),
    trad(22, 'emergencia.8.titulo', 'emergencia',
      'Ataque Epiléptico', 'Epileptic Seizure',
      'Epileptisk Anfall', 'Crise Épileptique', 'Atac Epilèptic', 'Epileptisk Anfald'),
    trad(23, 'emergencia.8.descripcion', 'emergencia',
      'Protege a la persona de golpes. No la sujetes ni introduzcas nada en la boca.',
      'Protect the person from impacts. Do not restrain them or put anything in their mouth.',
      'Beskytt personen mot slag. Ikke hold ham/henne fast eller stikk noe i munnen.',
      'Protégez la personne des chocs. Ne la retenez pas et n\'introduisez rien dans la bouche.',
      'Protegeix la persona de cops. No la subjectis ni introdueixis res a la boca.',
      'Beskyt personen mod slag. Hold dem ikke fast og sæt ingenting i munden.'),
    trad(24, 'emergencia.8.informacion', 'emergencia',
      'Duración de las convulsiones\nSi es la primera vez o tiene historial de epilepsia\nSi ha perdido el conocimiento\nSi hay lesiones tras la convulsión',
      'Duration of the seizures\nIf it is the first time or has a history of epilepsy\nIf they have lost consciousness\nIf there are injuries after the seizure',
      'Varighet av anfallet\nOm det er første gang eller har epilepsihistorikk\nOm bevisstheten er tapt\nOm det er skader etter anfallet',
      'Durée des convulsions\nSi c\'est la première fois ou s\'il a des antécédents d\'épilepsie\nS\'il a perdu connaissance\nS\'il y a des blessures après la convulsion',
      'Durada de les convulsions\nSi és la primera vegada o té historial d\'epilèpsia\nSi ha perdut el coneixement\nSi hi ha lesions després de la convulsió',
      'Anfaldets varighed\nOm det er første gang eller har epilepsihistorik\nOm bevidstheden er tabt\nOm der er skader efter anfallet'),
    trad(25, 'emergencia.9.titulo', 'emergencia',
      'Parada Cardiorrespiratoria', 'Cardiac Arrest',
      'Hjertestans', 'Arrêt Cardio-Respiratoire', 'Aturada Cardiorespiratòria', 'Hjertestop'),
    trad(26, 'emergencia.9.descripcion', 'emergencia',
      'Llama al 112 e inicia RCP inmediatamente (30 compresiones / 2 ventilaciones).',
      'Call 112 and start CPR immediately (30 compressions / 2 ventilations).',
      'Ring 112 og start HLR umiddelbart (30 kompresjoner / 2 innblåsninger).',
      'Appelez le 112 et commencez la RCP immédiatement (30 compressions / 2 ventilations).',
      'Truca al 112 i inicia RCP immediatament (30 compressions / 2 ventilacions).',
      'Ring 112 og påbegynd HLR straks (30 kompressioner / 2 indblæsninger).'),
    trad(27, 'emergencia.9.informacion', 'emergencia',
      'La persona NO respira o respira de forma anormal\nEstá inconsciente, no responde a estímulos\nSi ya has iniciado o iniciarás RCP (30 compresiones / 2 ventilaciones)\nSi hay un DEA (desfibrilador) disponible cerca',
      'The person is NOT breathing or breathing abnormally\nUnconscious, does not respond to stimuli\nIf you have started or will start CPR (30 compressions / 2 ventilations)\nIf there is an AED (defibrillator) available nearby',
      'Personen puster IKKE eller puster unormalt\nEr bevisstløs, reagerer ikke på stimuli\nOm du har startet eller vil starte HLR (30 kompresjoner / 2 innblåsninger)\nOm det er en AED (hjertestarter) tilgjengelig i nærheten',
      'La personne ne respire PAS ou respire de façon anormale\nEst inconsciente, ne répond pas aux stimuli\nSi vous avez commencé ou commencerez la RCP (30 compressions / 2 ventilations)\nS\'il y a un DAE (défibrillateur) disponible à proximité',
      'La persona NO respira o respira de forma anormal\nEstà inconscient, no respon a estímuls\nSi ja has iniciat o iniciàs RCP (30 compressions / 2 ventilacions)\nSi hi ha un DEA (desfibril·lador) disponible a prop',
      'Personen puster IKKE eller puster unormalt\nEr bevidstløs, reagerer ikke på stimuli\nOm du har påbegyndt eller vil påbegynde HLR (30 kompressioner / 2 indblæsninger)\nOm der er en AED (hjertestarter) tilgængeligt i nærheden'),
    trad(28, 'emergencia.10.titulo', 'emergencia',
      'Inconsciente pero Respirando', 'Unconscious but Breathing',
      'Bevisstløs men Puster', 'Inconscient mais Respire', 'Inconscient però Respirant', 'Bevidstløs men Vejrtrækker'),
    trad(29, 'emergencia.10.descripcion', 'emergencia',
      'Coloque en Posición Lateral de Seguridad (PLS) y vigile la respiración.',
      'Place in Recovery Position and monitor breathing.',
      'Legg i stabilt sideleie og overvåk pusten.',
      'Placez en Position Latérale de Sécurité (PLS) et surveillez la respiration.',
      'Col·loqueu en Posició Lateral de Seguretat (PLS) i vigileu la respiració.',
      'Placer i Stabilt Sideleje og overvåg vejrtrækningen.'),
    trad(30, 'emergencia.10.informacion', 'emergencia',
      'La persona está inconsciente pero respira\nYa la ha colocado en Posición Lateral de Seguridad (PLS)\nHace cuánto tiempo perdió la consciencia\nSi hay lesiones visibles (golpes en la cabeza, sangrado, etc.)',
      'The person is unconscious but breathing\nHas already been placed in Recovery Position\nHow long ago they lost consciousness\nIf there are visible injuries (head blows, bleeding, etc.)',
      'Personen er bevisstløs men puster\nEr allerede lagt i stabilt sideleie\nHvor lenge siden bevisstheten ble tapt\nOm det er synlige skader (hodeskader, blødning, etc.)',
      'La personne est inconsciente mais respire\nA déjà été placée en Position Latérale de Sécurité (PLS)\nDepuis combien de temps elle a perdu connaissance\nS\'il y a des blessures visibles (coups à la tête, saignement, etc.)',
      'La persona és inconscient però respira\nJa s\'ha col·locat en Posició Lateral de Seguretat (PLS)\nFa quant temps va perdre la consciència\nSi hi ha lesions visibles (cops al cap, sagnat, etc.)',
      'Personen er bevidstløs men vejrtrækker\nEr allerede lagt i stabilt sideleje\nHvor længe siden vedkommende mistede bevidstheden\nOm der er synlige skader (slag til hovedet, blødning, osv.)'),
  ]);
  console.log('✓ Emergencias (1-30)');

  // nodos (31-35)
  await Promise.all([
    trad(31, 'nodo.1.pregunta', 'nodo',
      '¿Es el entorno seguro para mí y para la víctima?',
      'Is the environment safe for me and the victim?',
      'Er omgivelsene trygge for meg og offeret?',
      'L\'environnement est-il sécurisé pour moi et pour la victime ?',
      'L\'entorn és segur per a mi i per a la víctima?',
      'Er omgivelserne sikre for mig og offeret?'),
    trad(32, 'nodo.2.pregunta', 'nodo',
      '¿La víctima responde a estímulos al preguntarle "¿Está usted bien?" y sacudirla suavemente?',
      'Does the victim respond to stimuli when asked "Are you okay?" and gently shaken?',
      'Reagerer offeret på stimuli når du spør "Har du det bra?" og rister det forsiktig?',
      'La victime répond-elle aux stimuli quand on lui demande "Ça va ?" et qu\'on la secoue doucement ?',
      'La víctima respon a estímuls en preguntar-li "Esteu bé?" i sacsejar-la suaument?',
      'Reagerer offeret på stimuli, når du spørger "Har du det godt?" og ryster vedkommende forsigtigt?'),
    trad(33, 'nodo.3.pregunta', 'nodo',
      '¿Qué ha pasado? Seleccione lo que mejor describe la situación:',
      'What happened? Select what best describes the situation:',
      'Hva har skjedd? Velg det som best beskriver situasjonen:',
      'Que s\'est-il passé ? Sélectionnez ce qui décrit le mieux la situation :',
      'Què ha passat? Seleccioneu el que millor descriu la situació:',
      'Hvad er der sket? Vælg det, der bedst beskriver situationen:'),
    trad(34, 'nodo.4.pregunta', 'nodo',
      '¿Puede hablar o toser? (Si se lleva las manos al cuello y no puede, es atragantamiento total)',
      'Can they speak or cough? (If hands go to throat and they cannot, it is complete choking)',
      'Kan de snakke eller hoste? (Hvis de holder seg for halsen og ikke kan, er det total kvelning)',
      'Peut-il parler ou tousser ? (S\'il se tient le cou et ne peut pas, c\'est un étouffement total)',
      'Pot parlar o tossir? (Si es porta les mans al coll i no pot, és ofegament total)',
      'Kan vedkommende tale eller hoste? (Hvis de holder sig til halsen og ikke kan, er det total kvælning)'),
    trad(35, 'nodo.5.pregunta', 'nodo',
      'Tras abrir la vía aérea, ¿respira con normalidad?\n(Ver, oír, sentir durante 10 segundos)',
      'After opening the airway, are they breathing normally?\n(Look, listen, feel for 10 seconds)',
      'Etter å ha åpnet luftveien, puster vedkommende normalt?\n(Se, høre, kjenne i 10 sekunder)',
      'Après avoir ouvert les voies respiratoires, respire-t-il normalement ?\n(Voir, entendre, sentir pendant 10 secondes)',
      'Després d\'obrir la via aèria, respira amb normalitat?\n(Veure, sentir, notar durant 10 segons)',
      'Efter åbning af luftvejen, vejrtrækker vedkommende normalt?\n(Se, høre, mærke i 10 sekunder)'),
  ]);
  console.log('✓ Nodos (31-35)');

  // opciones (36-49)
  await Promise.all([
    trad(36, 'opcion.1.texto', 'opcion',
      'Sí, el entorno es seguro', 'Yes, the environment is safe',
      'Ja, omgivelsene er trygge', 'Oui, l\'environnement est sécurisé', 'Sí, l\'entorn és segur', 'Ja, omgivelserne er sikre'),
    trad(37, 'opcion.2.texto', 'opcion',
      'No, hay peligro (incendio, tráfico, cables, etc.)', 'No, there is danger (fire, traffic, cables, etc.)',
      'Nei, det er fare (brann, trafikk, kabler, etc.)', 'Non, il y a un danger (incendie, trafic, câbles, etc.)',
      'No, hi ha perill (incendi, trànsit, cables, etc.)', 'Nej, der er fare (brand, trafik, kabler, osv.)'),
    trad(38, 'opcion.3.texto', 'opcion',
      'Sí, responde (consciente)', 'Yes, responds (conscious)',
      'Ja, reagerer (bevisst)', 'Oui, répond (conscient)', 'Sí, respon (conscient)', 'Ja, reagerer (bevidst)'),
    trad(39, 'opcion.4.texto', 'opcion',
      'No responde (inconsciente)', 'Does not respond (unconscious)',
      'Reagerer ikke (bevisstløs)', 'Ne répond pas (inconscient)', 'No respon (inconscient)', 'Reagerer ikke (bevidstløs)'),
    trad(40, 'opcion.5.texto', 'opcion',
      'Habla o tose con normalidad', 'Speaks or coughs normally',
      'Snakker eller hoster normalt', 'Parle ou tousse normalement', 'Parla o tosseix amb normalitat', 'Taler eller hoster normalt'),
    trad(41, 'opcion.6.texto', 'opcion',
      'Tiene dolor u opresión en el pecho', 'Has chest pain or tightness',
      'Har brystsmerter eller trykk i brystet', 'A des douleurs ou une oppression thoracique',
      'Té dolor o opressió al pit', 'Har brystsmerter eller trykken i brystet'),
    trad(42, 'opcion.7.texto', 'opcion',
      'Tiene debilidad en un lado del cuerpo o dificultad para hablar',
      'Has weakness on one side of body or difficulty speaking',
      'Har svakhet på den ene siden av kroppen eller vansker med å snakke',
      'A une faiblesse d\'un côté du corps ou des difficultés à parler',
      'Té debilitat en un costat del cos o dificultat per parlar',
      'Har svaghed på den ene side af kroppen eller talebesvær'),
    trad(43, 'opcion.8.texto', 'opcion',
      'Presenta hemorragias externas', 'Has external bleeding',
      'Har ekstern blødning', 'Présente des hémorragies externes', 'Presenta hemorràgies externes', 'Har ekstern blødning'),
    trad(44, 'opcion.9.texto', 'opcion',
      'Es diabético con sudor frío y temblores', 'Diabetic with cold sweat and tremors',
      'Er diabetiker med kaldsvette og skjelvinger', 'Est diabétique avec sueurs froides et tremblements',
      'És diabètic amb suor freda i tremolors', 'Er diabetiker med koldsved og rysteture'),
    trad(45, 'opcion.10.texto', 'opcion',
      'Otra emergencia', 'Other emergency',
      'Annen nødsituasjon', 'Autre urgence', 'Altra emergència', 'Anden nødsituation'),
    trad(46, 'opcion.11.texto', 'opcion',
      'Sí, puede hablar o toser', 'Yes, can speak or cough',
      'Ja, kan snakke eller hoste', 'Oui, peut parler ou tousser', 'Sí, pot parlar o tossir', 'Ja, kan tale eller hoste'),
    trad(47, 'opcion.12.texto', 'opcion',
      'No puede hablar ni toser - Se lleva las manos al cuello',
      'Cannot speak or cough – Hands go to throat',
      'Kan ikke snakke eller hoste – holder seg for halsen',
      'Ne peut ni parler ni tousser – Se tient le cou',
      'No pot parlar ni tossir - Es porta les mans al coll',
      'Kan ikke tale eller hoste – holder sig til halsen'),
    trad(48, 'opcion.13.texto', 'opcion',
      'No respira o respiración anormal → PARADA CARDÍACA',
      'Not breathing or abnormal breathing → CARDIAC ARREST',
      'Puster ikke eller unormal pust → HJERTESTANS',
      'Ne respire pas ou respiration anormale → ARRÊT CARDIAQUE',
      'No respira o respiració anormal → ATURADA CARDÍACA',
      'Vejrtrækker ikke eller unormal vejrtrækning → HJERTESTOP'),
    trad(49, 'opcion.14.texto', 'opcion',
      'Sí, respira normalmente', 'Yes, breathing normally',
      'Ja, puster normalt', 'Oui, respire normalement', 'Sí, respira normalment', 'Ja, vejrtrækker normalt'),
  ]);
  console.log('✓ Opciones (36-49)');

  // guias (50-61)
  await Promise.all([
    trad(50, 'guia.1.titulo', 'guia',
      'Infarto', 'Heart Attack', 'Hjerteinfarkt', 'Crise Cardiaque', 'Infart', 'Hjerteanfald'),
    trad(51, 'guia.1.descripcion', 'guia',
      'Guía de actuación ante un posible infarto de miocardio.',
      'Action guide for a possible myocardial infarction.',
      'Handlingsguide ved mulig hjerteinfarkt.',
      'Guide d\'action pour un possible infarctus du myocarde.',
      'Guia d\'actuació davant d\'un possible infart de miocardi.',
      'Handlingsguide ved muligt hjerteinfarkt.'),
    trad(52, 'guia.2.titulo', 'guia',
      'Parada Cardiorrespiratoria', 'Cardiac Arrest',
      'Hjertestans', 'Arrêt Cardio-Respiratoire', 'Aturada Cardiorespiratòria', 'Hjertestop'),
    trad(53, 'guia.2.descripcion', 'guia',
      'Guía de actuación ante una parada cardiorrespiratoria.',
      'Action guide for a cardiac arrest.',
      'Handlingsguide ved hjertestans.',
      'Guide d\'action pour un arrêt cardio-respiratoire.',
      'Guia d\'actuació davant d\'una aturada cardiorespiratòria.',
      'Handlingsguide ved hjertestop.'),
    trad(54, 'guia.3.titulo', 'guia',
      'Ictus', 'Stroke', 'Hjerneslag', 'AVC', 'Ictus', 'Slagtilfælde'),
    trad(55, 'guia.3.descripcion', 'guia',
      'Guía de actuación ante un posible ictus o AVC.',
      'Action guide for a possible stroke or CVA.',
      'Handlingsguide ved mulig hjerneslag.',
      'Guide d\'action pour un possible AVC.',
      'Guia d\'actuació davant d\'un possible ictus o AVC.',
      'Handlingsguide ved muligt slagtilfælde.'),
    trad(56, 'guia.4.titulo', 'guia',
      'Ataque Epiléptico', 'Epileptic Seizure',
      'Epileptisk Anfall', 'Crise Épileptique', 'Atac Epilèptic', 'Epileptisk Anfald'),
    trad(57, 'guia.4.descripcion', 'guia',
      'Guía de actuación ante un ataque epiléptico.',
      'Action guide for an epileptic seizure.',
      'Handlingsguide ved epileptisk anfall.',
      'Guide d\'action pour une crise épileptique.',
      'Guia d\'actuació davant d\'un atac epilèptic.',
      'Handlingsguide ved epileptisk anfald.'),
    trad(58, 'guia.5.titulo', 'guia',
      'Obstrucción de Vía Aérea', 'Airway Obstruction',
      'Luftveisobstruksjon', 'Obstruction des Voies Aériennes', 'Obstrucció de Vies Aèries', 'Luftvejsobstruktion'),
    trad(59, 'guia.5.descripcion', 'guia',
      'Guía de actuación ante un atragantamiento.',
      'Action guide for choking.',
      'Handlingsguide ved kvelning.',
      'Guide d\'action pour un étouffement.',
      'Guia d\'actuació davant d\'un ofegament.',
      'Handlingsguide ved kvælning.'),
    trad(60, 'guia.6.titulo', 'guia',
      'Hemorragia Severa', 'Severe Bleeding',
      'Alvorlig Blødning', 'Hémorragie Sévère', 'Hemorràgia Severa', 'Svær Blødning'),
    trad(61, 'guia.6.descripcion', 'guia',
      'Guía de actuación ante una hemorragia severa.',
      'Action guide for severe bleeding.',
      'Handlingsguide ved alvorlig blødning.',
      'Guide d\'action pour une hémorragie sévère.',
      'Guia d\'actuació davant d\'una hemorràgia severa.',
      'Handlingsguide ved svær blødning.'),
  ]);
  console.log('✓ Guías (50-61)');

  // pasos (62-99)
  await Promise.all([
    trad(62, 'paso.1.titulo', 'paso',
      'Activar servicios de emergencia', 'Activate emergency services',
      'Aktiver nødetjenester', 'Activer les services d\'urgence', 'Activar serveis d\'emergència', 'Aktivér nødtjenester'),
    trad(63, 'paso.1.contenido', 'paso',
      'Activar inmediatamente los servicios de emergencia (112)', 'Immediately activate emergency services (112)',
      'Aktiver umiddelbart nødetjenestene (112)', 'Activer immédiatement les services d\'urgence (112)',
      'Activar immediatament els serveis d\'emergència (112)', 'Aktivér straks nødtjenesterne (112)'),
    trad(64, 'paso.2.titulo', 'paso',
      'Mantener en reposo', 'Keep at rest',
      'Hold i ro', 'Garder au repos', 'Mantenir en repòs', 'Hold i ro'),
    trad(65, 'paso.2.contenido', 'paso',
      'Mantener a la persona en reposo y tranquila', 'Keep the person at rest and calm',
      'Hold personen i ro og avslappet', 'Garder la personne au repos et calme',
      'Mantenir la persona en repòs i tranquil·la', 'Hold personen i ro og afslappet'),
    trad(66, 'paso.3.titulo', 'paso',
      'Vigilar consciencia', 'Monitor consciousness',
      'Overvåk bevissthet', 'Surveiller la conscience', 'Vigilar la consciència', 'Overvåg bevidsthed'),
    trad(67, 'paso.3.contenido', 'paso',
      'Vigilar el estado de conciencia y respiración', 'Monitor the state of consciousness and breathing',
      'Overvåk bevissthetsnivå og pust', 'Surveiller l\'état de conscience et la respiration',
      'Vigilar l\'estat de consciència i la respiració', 'Overvåg bevidsthedsniveau og vejrtrækning'),
    trad(68, 'paso.4.titulo', 'paso',
      'Preparar RCP', 'Prepare CPR',
      'Forbered HLR', 'Préparer la RCP', 'Preparar RCP', 'Forbered HLR'),
    trad(69, 'paso.4.contenido', 'paso',
      'Prepararse para iniciar RCP si pierde el conocimiento', 'Be ready to start CPR if they lose consciousness',
      'Vær klar til å starte HLR hvis bevisstheten tapes',
      'Se préparer à commencer la RCP en cas de perte de connaissance',
      'Preparar-se per iniciar RCP si perd el coneixement',
      'Vær parat til at påbegynde HLR, hvis bevidstheden mistes'),
    trad(70, 'paso.5.titulo', 'paso',
      'Llamar a emergencias', 'Call emergency services',
      'Ring nødnummeret', 'Appeler les secours', 'Trucar a emergències', 'Ring til nødtjenester'),
    trad(71, 'paso.5.contenido', 'paso',
      'Llamar inmediatamente a emergencias (112)', 'Immediately call emergency services (112)',
      'Ring umiddelbart til nødnummeret (112)', 'Appeler immédiatement les secours (112)',
      'Trucar immediatament a emergències (112)', 'Ring straks til nødtjenesterne (112)'),
    trad(72, 'paso.6.titulo', 'paso',
      'Iniciar RCP', 'Start CPR',
      'Start HLR', 'Commencer la RCP', 'Iniciar RCP', 'Påbegynd HLR'),
    trad(73, 'paso.6.contenido', 'paso',
      'Iniciar maniobras de RCP (30 compresiones / 2 ventilaciones)',
      'Start CPR (30 compressions / 2 ventilations)',
      'Start HLR (30 kompresjoner / 2 innblåsninger)',
      'Commencer les manœuvres de RCP (30 compressions / 2 ventilations)',
      'Iniciar maniobres de RCP (30 compressions / 2 ventilacions)',
      'Påbegynd HLR (30 kompressioner / 2 indblæsninger)'),
    trad(74, 'paso.7.titulo', 'paso',
      'Usar DEA', 'Use AED', 'Bruk AED', 'Utiliser le DAE', 'Usar DEA', 'Brug AED'),
    trad(75, 'paso.7.contenido', 'paso',
      'Utilizar un DEA si está disponible', 'Use an AED if available',
      'Bruk en AED (hjertestarter) hvis tilgjengelig', 'Utiliser un DAE si disponible',
      'Utilitzar un DEA si està disponible', 'Brug en AED (hjertestarter), hvis tilgængelig'),
    trad(76, 'paso.8.titulo', 'paso',
      'Llamar al 112', 'Call 112', 'Ring 112', 'Appeler le 112', 'Trucar al 112', 'Ring 112'),
    trad(77, 'paso.8.contenido', 'paso',
      'Contactar a emergencias de inmediato (112)', 'Contact emergency services immediately (112)',
      'Kontakt nødetjenesten umiddelbart (112)', 'Contacter les secours immédiatement (112)',
      'Contactar emergències de seguida (112)', 'Kontakt nødtjenesten straks (112)'),
    trad(78, 'paso.9.titulo', 'paso',
      'No esperar', 'Do not wait', 'Ikke vent', 'Ne pas attendre', 'No esperar', 'Vent ikke'),
    trad(79, 'paso.9.contenido', 'paso',
      'No esperar: el tiempo es crítico para limitar el daño cerebral',
      'Do not wait: time is critical to limit brain damage',
      'Ikke vent: tid er avgjørende for å begrense hjerneskaden',
      'Ne pas attendre : le temps est critique pour limiter les dommages cérébraux',
      'No esperar: el temps és crític per limitar el dany cerebral',
      'Vent ikke: tid er afgørende for at begrænse hjerneskaden'),
    trad(80, 'paso.10.titulo', 'paso',
      'Proteger la cabeza', 'Protect the head',
      'Beskytt hodet', 'Protéger la tête', 'Protegir el cap', 'Beskyt hovedet'),
    trad(81, 'paso.10.contenido', 'paso',
      'Proteger la cabeza y evitar objetos duros alrededor',
      'Protect the head and remove hard objects from the area',
      'Beskytt hodet og fjern harde gjenstander i nærheten',
      'Protéger la tête et éviter les objets durs autour',
      'Protegir el cap i evitar objectes durs al voltant',
      'Beskyt hovedet og fjern hårde genstande i nærheden'),
    trad(82, 'paso.11.titulo', 'paso',
      'No intervenir', 'Do not intervene',
      'Ikke gripe inn', 'Ne pas intervenir', 'No intervenir', 'Grib ikke ind'),
    trad(83, 'paso.11.contenido', 'paso',
      'No introducir objetos en la boca ni sujetar al paciente',
      'Do not put objects in the mouth or restrain the patient',
      'Ikke stikk gjenstander i munnen og ikke hold pasienten fast',
      'Ne pas mettre d\'objets dans la bouche ni retenir le patient',
      'No introduir objectes a la boca ni subjectar el pacient',
      'Sæt ikke genstande i munden og hold ikke patienten fast'),
    trad(84, 'paso.12.titulo', 'paso',
      'Posición lateral', 'Recovery position',
      'Sideleie', 'Position latérale', 'Posició lateral', 'Sideleje'),
    trad(85, 'paso.12.contenido', 'paso',
      'Tras la convulsión, colocar a la persona de lado',
      'After the seizure, place the person on their side',
      'Etter anfallet, legg personen på siden',
      'Après la convulsion, placer la personne sur le côté',
      'Després de la convulsió, col·locar la persona de costat',
      'Efter anfallet, læg personen på siden'),
    trad(86, 'paso.13.titulo', 'paso',
      'Animar a toser', 'Encourage coughing',
      'Oppmuntre til hosting', 'Encourager la toux', 'Animar a tossir', 'Opfordr til at hoste'),
    trad(87, 'paso.13.contenido', 'paso',
      'Si puede toser, animar a que lo haga', 'If they can cough, encourage them to do so',
      'Hvis vedkommende kan hoste, oppmuntre dem til å gjøre det',
      'S\'il peut tousser, l\'encourager à le faire',
      'Si pot tossir, animar-lo que ho faci',
      'Hvis vedkommende kan hoste, opfordr dem til at gøre det'),
    trad(88, 'paso.14.titulo', 'paso',
      'Palmadas', 'Back blows', 'Ryggslag', 'Claques dans le dos', 'Cops a l\'esquena', 'Rygslag'),
    trad(89, 'paso.14.contenido', 'paso',
      'Si no, aplicar 5 palmadas firmes en la espalda',
      'If not, apply 5 firm back blows between shoulder blades',
      'Ellers, gi 5 kraftige slag på ryggen mellom skulderbladene',
      'Sinon, appliquer 5 claques fermes dans le dos',
      'Si no, aplicar 5 cops ferms a l\'esquena',
      'Ellers, giv 5 kraftige slag på ryggen mellem skulderbladene'),
    trad(90, 'paso.15.titulo', 'paso',
      'Heimlich', 'Heimlich', 'Heimlich', 'Heimlich', 'Heimlich', 'Heimlich'),
    trad(91, 'paso.15.contenido', 'paso',
      'Aplicar compresiones abdominales (Maniobra de Heimlich)',
      'Apply abdominal thrusts (Heimlich maneuver)',
      'Utfør abdominale kompresjoner (Heimlich-manøveren)',
      'Appliquer des compressions abdominales (Manœuvre de Heimlich)',
      'Aplicar compressions abdominals (Maniobra de Heimlich)',
      'Udfør mavekompressioner (Heimlich-manøvren)'),
    trad(92, 'paso.16.titulo', 'paso',
      'Llamar al 112', 'Call 112', 'Ring 112', 'Appeler le 112', 'Trucar al 112', 'Ring 112'),
    trad(93, 'paso.16.contenido', 'paso',
      'Llamar inmediatamente al 112', 'Call 112 immediately',
      'Ring umiddelbart til 112', 'Appeler immédiatement le 112',
      'Trucar immediatament al 112', 'Ring straks til 112'),
    trad(94, 'paso.17.titulo', 'paso',
      'Compresión directa', 'Direct pressure',
      'Direkte trykk', 'Pression directe', 'Compressió directa', 'Direkte tryk'),
    trad(95, 'paso.17.contenido', 'paso',
      'Aplicar compresión directa y continua sobre la herida con un paño limpio',
      'Apply direct and continuous pressure on the wound with a clean cloth',
      'Påfør direkte og vedvarende trykk på såret med et rent klede',
      'Appliquer une pression directe et continue sur la blessure avec un tissu propre',
      'Aplicar compressió directa i contínua sobre la ferida amb un drap net',
      'Påfør direkte og vedvarende tryk på såret med et rent klæde'),
    trad(96, 'paso.18.titulo', 'paso',
      'Añadir capas', 'Add layers',
      'Legg til lag', 'Ajouter des couches', 'Afegir capes', 'Tilføj lag'),
    trad(97, 'paso.18.contenido', 'paso',
      'Si la sangre empapa el paño, añadir más capas sin quitar las anteriores',
      'If blood soaks through, add more layers without removing the previous ones',
      'Hvis blodet gjennombløter klede, legg til flere lag uten å fjerne de forrige',
      'Si le sang imprègne le tissu, ajouter plus de couches sans enlever les précédentes',
      'Si la sang empapa el drap, afegir més capes sense treure les anteriors',
      'Hvis blodet gennemvæder klædet, tilføj flere lag uden at fjerne de tidligere'),
    trad(98, 'paso.19.titulo', 'paso',
      'Elevar extremidad', 'Elevate the limb',
      'Løft ekstremiteten', 'Élever le membre', 'Elevar extremitat', 'Løft ekstremiteten'),
    trad(99, 'paso.19.contenido', 'paso',
      'Elevar la extremidad lesionada si es posible y no hay fractura',
      'Elevate the injured limb if possible and there is no fracture',
      'Løft den skadede ekstremiteten hvis mulig og det ikke er brudd',
      'Élever le membre blessé si possible et en l\'absence de fracture',
      'Elevar l\'extremitat lesionada si és possible i no hi ha fractura',
      'Løft den skadede ekstremitet, hvis muligt og der ikke er brud'),
  ]);
  console.log('✓ Pasos (62-99)');

  // herramientas (100-113)
  await Promise.all([
    trad(100, 'herramienta.1.nombre', 'herramienta',
      'Asistente llamada 112', '112 Call Assistant',
      'Assistent for 112-anrop', 'Assistant appel 112', 'Assistent trucada 112', 'Assistent til 112-opkald'),
    trad(101, 'herramienta.1.descripcion', 'herramienta',
      'Geolocalización automática y guía estructurada para comunicarte con emergencias',
      'Automatic geolocation and structured guide to communicate with emergency services',
      'Automatisk geolokalisering og strukturert guide for å kommunisere med nødetjenester',
      'Géolocalisation automatique et guide structuré pour communiquer avec les secours',
      'Geolocalització automàtica i guia estructurada per comunicar-te amb emergències',
      'Automatisk geolokalisering og struktureret guide til at kommunikere med nødtjenester'),
    trad(102, 'herramienta.2.nombre', 'herramienta',
      'Asistente de RCP', 'CPR Assistant',
      'HLR-assistent', 'Assistant RCP', 'Assistent de RCP', 'HLR-assistent'),
    trad(103, 'herramienta.2.descripcion', 'herramienta',
      'Metrónomo 100 rpm, medidor de profundidad, temporizador de ciclos y contador',
      '100 bpm metronome, depth meter, cycle timer and counter',
      'Metronom 100 bpm, dybdemåler, syklustimer og teller',
      'Métronome 100 bpm, mesureur de profondeur, minuteur de cycles et compteur',
      'Metrònom 100 rpm, mesurador de profunditat, temporitzador de cicles i comptador',
      'Metronom 100 bpm, dybdemåler, cyklustimer og tæller'),
    trad(104, 'herramienta.3.nombre', 'herramienta',
      'Medidor de frecuencia cardíaca', 'Heart rate monitor',
      'Pulsmåler', 'Mesureur de fréquence cardiaque', 'Mesurador de freqüència cardíaca', 'Pulsmåler'),
    trad(105, 'herramienta.3.descripcion', 'herramienta',
      'Medición de la frecuencia cardíaca por fotopletismografía (cámara)',
      'Heart rate measurement by photoplethysmography (camera)',
      'Måling av hjerterytme via fotoplethysmografi (kamera)',
      'Mesure de la fréquence cardiaque par photopléthysmographie (caméra)',
      'Mesura de la freqüència cardíaca per fotopletismografia (càmera)',
      'Måling af hjerterytme via fotoplethysmografi (kamera)'),
    trad(106, 'herramienta.4.nombre', 'herramienta',
      'Test de detección de Ictus', 'Stroke detection test',
      'Test for slagdeteksjon', 'Test de détection d\'AVC', 'Test de detecció d\'Ictus', 'Test for slagtilfælde-detektion'),
    trad(107, 'herramienta.4.descripcion', 'herramienta',
      'Método FAST para identificar rápidamente un posible accidente cerebrovascular',
      'FAST method to quickly identify a possible stroke',
      'FAST-metoden for raskt å identifisere et mulig hjerneslag',
      'Méthode FAST pour identifier rapidement un possible AVC',
      'Mètode FAST per identificar ràpidament un possible accident cerebrovascular',
      'FAST-metoden til hurtigt at identificere et muligt slagtilfælde'),
    trad(108, 'herramienta.5.nombre', 'herramienta',
      'Calculadora de quemaduras', 'Burns calculator',
      'Brannskadekalkulator', 'Calculateur de brûlures', 'Calculadora de cremades', 'Brandsårsberegner'),
    trad(109, 'herramienta.5.descripcion', 'herramienta',
      'Estima el porcentaje de superficie corporal quemada con la Regla de los 9',
      'Estimates the percentage of burned body surface using the Rule of Nines',
      'Estimerer prosentandelen av forbrent kroppsoverflate med 9-regelen',
      'Estime le pourcentage de surface corporelle brûlée avec la Règle des 9',
      'Estima el percentatge de superfície corporal cremada amb la Regla dels 9',
      'Estimerer procentdelen af forbrændt kropsoverflade med 9-reglen'),
    trad(110, 'herramienta.6.nombre', 'herramienta',
      'Registro de exploración secundaria', 'Secondary survey log',
      'Sekundærundersøkelseslogg', 'Registre d\'examen secondaire',
      'Registre d\'exploració secundària', 'Log over sekundær undersøgelse'),
    trad(111, 'herramienta.6.descripcion', 'herramienta',
      'Anota signos, síntomas y observaciones para entregar al personal sanitario',
      'Record signs, symptoms and observations for medical personnel',
      'Noter tegn, symptomer og observasjoner for å gi til helsepersonell',
      'Note les signes, symptômes et observations pour les remettre au personnel médical',
      'Anota signes, símptomes i observacions per lliurar al personal sanitari',
      'Notér tegn, symptomer og observationer til udlevering til sundhedspersonalet'),
    trad(112, 'herramienta.7.nombre', 'herramienta',
      'Ficha médica de emergencia', 'Emergency medical record',
      'Medisinsk nødkort', 'Fiche médicale d\'urgence', 'Fitxa mèdica d\'emergència', 'Medicinsk nødkort'),
    trad(113, 'herramienta.7.descripcion', 'herramienta',
      'Alergias, medicación y contactos de emergencia guardados en el dispositivo',
      'Allergies, medication and emergency contacts stored on the device',
      'Allergier, medisinering og nødkontakter lagret på enheten',
      'Allergies, médicaments et contacts d\'urgence enregistrés sur l\'appareil',
      'Al·lèrgies, medicació i contactes d\'emergència guardats al dispositiu',
      'Allergier, medicin og nødkontakter gemt på enheden'),
  ]);
  console.log('✓ Herramientas (100-113)');

  // ui (114-117), nav (118-120), cuestionario (121-122)
  await Promise.all([
    trad(114, 'ui.llamar112', 'ui',
      '¡LLAMA AL 112!', 'CALL 112!', 'RING 112!', 'APPELEZ LE 112 !', 'TRUCA AL 112!', 'RING 112!'),
    trad(115, 'ui.boton.anterior', 'ui',
      'Anterior', 'Previous', 'Forrige', 'Précédent', 'Anterior', 'Forrige'),
    trad(116, 'ui.boton.siguiente', 'ui',
      'Siguiente', 'Next', 'Neste', 'Suivant', 'Següent', 'Næste'),
    trad(117, 'ui.boton.reiniciar', 'ui',
      'Reiniciar', 'Restart', 'Start på nytt', 'Recommencer', 'Reiniciar', 'Genstart'),
    trad(118, 'nav.inicio', 'nav',
      'Inicio', 'Home', 'Hjem', 'Accueil', 'Inici', 'Hjem'),
    trad(119, 'nav.guias', 'nav',
      'Guías', 'Guides', 'Guider', 'Guides', 'Guies', 'Guider'),
    trad(120, 'nav.herramientas', 'nav',
      'Herramientas', 'Tools', 'Verktøy', 'Outils', 'Eines', 'Værktøjer'),
    trad(121, 'cuestionario.titulo', 'cuestionario',
      'Identificador de\nEmergencias', 'Emergency\nIdentifier',
      'Nødsituasjons-\nidentifikator', 'Identificateur\nd\'Urgences',
      'Identificador\nd\'Emergències', 'Nødsituations-\nidentifikator'),
    trad(122, 'cuestionario.preguntaAnterior', 'cuestionario',
      'Pregunta anterior', 'Previous question',
      'Forrige spørsmål', 'Question précédente', 'Pregunta anterior', 'Forrige spørgsmål'),
  ]);
  console.log('✓ UI / Nav / Cuestionario (114-122)');

  // resultado (123-137)
  await Promise.all([
    trad(123, 'resultado.tituloApp', 'resultado',
      'Identificador de Emergencias', 'Emergency Identifier',
      'Nødsituasjonsidentifikator', 'Identificateur d\'Urgences',
      'Identificador d\'Emergències', 'Nødsituationsidentifikator'),
    trad(124, 'resultado.llamarAhora', 'resultado',
      'LLAMA AL 112 AHORA', 'CALL 112 NOW',
      'RING 112 NÅ', 'APPELEZ LE 112 MAINTENANT', 'TRUCA AL 112 ARA', 'RING 112 NU'),
    trad(125, 'resultado.proporcionaInfo', 'resultado',
      'Proporciona esta información al operador:', 'Provide this information to the operator:',
      'Gi denne informasjonen til operatøren:', 'Fournissez ces informations à l\'opérateur :',
      'Proporciona aquesta informació a l\'operador:', 'Giv disse oplysninger til operatøren:'),
    trad(126, 'resultado.llamar', 'resultado',
      'Llamar al 112', 'Call 112', 'Ring 112', 'Appeler le 112', 'Trucar al 112', 'Ring 112'),
    trad(127, 'resultado.infoEspecifica', 'resultado',
      'Información específica para esta emergencia:', 'Specific information for this emergency:',
      'Spesifikk informasjon for denne nødsituasjonen:', 'Informations spécifiques pour cette urgence :',
      'Informació específica per a aquesta emergència:', 'Specifik information om denne nødsituation:'),
    trad(128, 'resultado.infoGeneral', 'resultado',
      'Información general a mencionar:', 'General information to mention:',
      'Generell informasjon å nevne:', 'Informations générales à mentionner :',
      'Informació general a mencionar:', 'Generel information at nævne:'),
    trad(129, 'resultado.noCuelgues', 'resultado',
      'NO CUELGUES. Permanece en línea y sigue las instrucciones del operador.',
      'DO NOT HANG UP. Stay on the line and follow the operator\'s instructions.',
      'IKKE LEGG PÅ. Bli på linjen og følg instruksjonene fra operatøren.',
      'NE RACCROCHEZ PAS. Restez en ligne et suivez les instructions de l\'opérateur.',
      'NO PENGIS. Mantén la línia i segueix les instruccions de l\'operador.',
      'LAG IKKE PÅ. Bliv på linjen og følg operatørens instruktioner.'),
    trad(130, 'resultado.reiniciar', 'resultado',
      'Reiniciar', 'Restart', 'Start på nytt', 'Recommencer', 'Reiniciar', 'Genstart'),
    trad(131, 'resultado.verGuia', 'resultado',
      'Ver guía completa', 'View full guide',
      'Se fullstendig guide', 'Voir le guide complet', 'Veure guia completa', 'Se den komplette guide'),
    trad(132, 'resultado.info1', 'resultado',
      'Ubicación exacta: calle, número, población y puntos de referencia',
      'Exact location: street, number, town and landmarks',
      'Nøyaktig adresse: gate, nummer, sted og referansepunkter',
      'Localisation exacte : rue, numéro, ville et points de repère',
      'Ubicació exacta: carrer, número, població i punts de referència',
      'Nøjagtig adresse: gade, nummer, by og referencepunkter'),
    trad(133, 'resultado.info2', 'resultado',
      'Qué ha ocurrido (accidente, desmayo, caída, etc.)',
      'What happened (accident, fainting, fall, etc.)',
      'Hva som har skjedd (ulykke, besvimelse, fall, etc.)',
      'Ce qui s\'est passé (accident, évanouissement, chute, etc.)',
      'Què ha ocorregut (accident, desmai, caiguda, etc.)',
      'Hvad der er sket (ulykke, besvimelse, fald, osv.)'),
    trad(134, 'resultado.info3', 'resultado',
      'Número de personas afectadas', 'Number of people affected',
      'Antall berørte personer', 'Nombre de personnes affectées',
      'Nombre de persones afectades', 'Antal berørte personer'),
    trad(135, 'resultado.info4', 'resultado',
      'Edad aproximada de la víctima', 'Approximate age of the victim',
      'Omtrentlig alder på offeret', 'Âge approximatif de la victime',
      'Edat aproximada de la víctima', 'Omtrentlig alder på offeret'),
    trad(136, 'resultado.info5', 'resultado',
      'Si está consciente o inconsciente', 'Whether conscious or unconscious',
      'Om vedkommende er bevisst eller bevisstløs', 'Si elle est consciente ou inconsciente',
      'Si està conscient o inconscient', 'Om vedkommende er bevidst eller bevidstløs'),
    trad(137, 'resultado.info6', 'resultado',
      'Si respira o no respira', 'Whether breathing or not',
      'Om vedkommende puster eller ikke puster', 'Si elle respire ou ne respire pas',
      'Si respira o no respira', 'Om vedkommende vejrtrækker eller ikke'),
  ]);
  console.log('✓ Resultado (123-137)');

  // guias list (138-140), guia detalle (141-144), herramientas list (145-151)
  await Promise.all([
    trad(138, 'guias.titulo', 'guias',
      'Guías de Emergencias', 'Emergency Guides',
      'Nødguider', 'Guides d\'Urgences', 'Guies d\'Emergències', 'Nødguider'),
    trad(139, 'guias.subtitulo', 'guias',
      'Selecciona la emergencia para ver la guía completa',
      'Select an emergency to see the full guide',
      'Velg nødsituasjonen for å se den fullstendige guiden',
      'Sélectionnez l\'urgence pour voir le guide complet',
      'Selecciona l\'emergència per veure la guia completa',
      'Vælg nødsituationen for at se den komplette guide'),
    trad(140, 'guias.tocaParaVer', 'guias',
      'Toca para ver la guía de actuación', 'Tap to view the action guide',
      'Trykk for å se handlingsguiden', 'Appuyez pour voir le guide d\'action',
      'Toca per veure la guia d\'actuació', 'Tryk for at se handlingsguiden'),
    trad(141, 'guia.comoDetectarlo', 'guia',
      'Cómo detectarlo', 'How to detect it',
      'Hvordan oppdage det', 'Comment le détecter', 'Com detectar-ho', 'Sådan opdager du det'),
    trad(142, 'guia.comoActuar', 'guia',
      'Cómo actuar', 'How to act',
      'Hvordan handle', 'Comment agir', 'Com actuar', 'Sådan handler du'),
    trad(143, 'guia.pasosASeguir', 'guia',
      'Pasos a seguir', 'Steps to follow',
      'Trinn å følge', 'Étapes à suivre', 'Passos a seguir', 'Trin at følge'),
    trad(144, 'guia.todosLosPasos', 'guia',
      'Todos los pasos:', 'All steps:',
      'Alle trinn:', 'Toutes les étapes :', 'Tots els passos:', 'Alle trin:'),
    trad(145, 'herramientas.titulo', 'herramientas',
      'Herramientas', 'Tools', 'Verktøy', 'Outils', 'Eines', 'Værktøjer'),
    trad(146, 'herramientas.subtitulo', 'herramientas',
      'Herramientas interactivas de soporte', 'Interactive support tools',
      'Interaktive støtteverktøy', 'Outils interactifs de support',
      'Eines interactives de suport', 'Interaktive støtteværktøjer'),
    trad(147, 'herramientas.cat.alerta', 'herramientas',
      'Gestión de Alerta y Ubicación', 'Alert and Location Management',
      'Varslings- og posisjonsadministrasjon', 'Gestion des Alertes et de la Localisation',
      'Gestió d\'Alerta i Ubicació', 'Alarm- og lokationsstyring'),
    trad(148, 'herramientas.cat.reaccion', 'herramientas',
      'Guías de Reacción Inmediata', 'Immediate Reaction Guides',
      'Guider for umiddelbar reaksjon', 'Guides de Réaction Immédiate',
      'Guies de Reacció Immediata', 'Guider til øjeblikkelig reaktion'),
    trad(149, 'herramientas.cat.diagnostico', 'herramientas',
      'Herramientas de Identificación y Diagnóstico', 'Identification and Diagnosis Tools',
      'Identifikasjons- og diagnoseverktøy', 'Outils d\'Identification et de Diagnostic',
      'Eines d\'Identificació i Diagnòstic', 'Identificerings- og diagnoseværktøjer'),
    trad(150, 'herramientas.cat.info', 'herramientas',
      'Información Médica Crítica', 'Critical Medical Information',
      'Kritisk medisinsk informasjon', 'Informations Médicales Critiques',
      'Informació Mèdica Crítica', 'Kritisk medicinsk information'),
    trad(151, 'herramientas.aviso', 'herramientas',
      'ℹ Acerca de las herramientas\n\nEstas herramientas aplican el protocolo PAS (Proteger-Alertar-Socorrer) y están diseñadas para asistir en situaciones de emergencia. Son de carácter orientativo y no sustituyen la atención médica profesional ni la llamada al 112.',
      'ℹ About the tools\n\nThese tools apply the PAS protocol (Protect-Alert-Assist) and are designed to assist in emergency situations. They are for guidance only and do not replace professional medical care or calling 112.',
      'ℹ Om verktøyene\n\nDisse verktøyene bruker PAS-protokollen (Beskytte-Varsle-Hjelpe) og er utformet for å hjelpe i nødsituasjoner. De er veiledende og erstatter ikke profesjonell medisinsk hjelp eller oppringning til 112.',
      'ℹ À propos des outils\n\nCes outils appliquent le protocole PAS (Protéger-Alerter-Secourir) et sont conçus pour aider dans les situations d\'urgence. Ils sont indicatifs et ne remplacent pas les soins médicaux professionnels ni l\'appel au 112.',
      'ℹ Sobre les eines\n\nAquestes eines apliquen el protocol PAS (Protegir-Alertar-Socórrer) i estan dissenyades per assistir en situacions d\'emergència. Són d\'orientació i no substitueixen l\'atenció mèdica professional ni la trucada al 112.',
      'ℹ Om værktøjerne\n\nDisse værktøjer anvender PAS-protokollen (Beskytte-Advare-Hjælpe) og er designet til at assistere i nødsituationer. De er vejledende og erstatter ikke professionel lægehjælp eller opkald til 112.'),
  ]);
  console.log('✓ Guías list / Guía detalle / Herramientas list (138-151)');

  // configuración (152-184)
  await Promise.all([
    trad(152, 'config.titulo', 'config',
      'Configuración', 'Settings', 'Innstillinger', 'Paramètres', 'Configuració', 'Indstillinger'),
    trad(153, 'config.idioma', 'config',
      'Idioma', 'Language', 'Språk', 'Langue', 'Idioma', 'Sprog'),
    trad(154, 'config.disponible', 'config',
      'Disponible', 'Available', 'Tilgjengelig', 'Disponible', 'Disponible', 'Tilgængeligt'),
    trad(155, 'config.noDescargado', 'config',
      'No descargado', 'Not downloaded', 'Ikke lastet ned', 'Non téléchargé', 'No descarregat', 'Ikke downloadet'),
    trad(156, 'config.apariencia', 'config',
      'Apariencia', 'Appearance', 'Utseende', 'Apparence', 'Aparença', 'Udseende'),
    trad(157, 'config.tamanoLetra', 'config',
      'Tamaño de letra', 'Font size', 'Skriftstørrelse', 'Taille de la police', 'Mida de lletra', 'Skriftstørrelse'),
    trad(158, 'config.tamano.pequeño', 'config',
      'Pequeño', 'Small', 'Liten', 'Petit', 'Petit', 'Lille'),
    trad(159, 'config.tamano.reducido', 'config',
      'Reducido', 'Reduced', 'Redusert', 'Réduit', 'Reduït', 'Reduceret'),
    trad(160, 'config.tamano.normal', 'config',
      'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal'),
    trad(161, 'config.tamano.grande', 'config',
      'Grande', 'Large', 'Stor', 'Grand', 'Gran', 'Stor'),
    trad(162, 'config.tamano.muyGrande', 'config',
      'Muy grande', 'Very large', 'Svært stor', 'Très grand', 'Molt gran', 'Meget stor'),
    trad(163, 'config.vistaPrevia', 'config',
      'Vista previa del texto en la aplicación.', 'Preview of text in the app.',
      'Forhåndsvisning av tekst i appen.', 'Aperçu du texte dans l\'application.',
      'Vista prèvia del text a l\'aplicació.', 'Forhåndsvisning af tekst i appen.'),
    trad(164, 'config.datosLocales', 'config',
      'Datos locales', 'Local data', 'Lokale data', 'Données locales', 'Dades locals', 'Lokale data'),
    trad(165, 'config.avisoLegal', 'config',
      'Aviso legal', 'Legal notice', 'Juridisk merknad', 'Mentions légales', 'Avís legal', 'Juridisk meddelelse'),
    trad(166, 'config.avisoAceptado', 'config',
      'Aceptado', 'Accepted', 'Akseptert', 'Accepté', 'Acceptat', 'Accepteret'),
    trad(167, 'config.avisoNoAceptado', 'config',
      'No aceptado todavía', 'Not yet accepted',
      'Ikke akseptert ennå', 'Pas encore accepté', 'No acceptat encara', 'Endnu ikke accepteret'),
    trad(168, 'config.restablecer', 'config',
      'Restablecer', 'Reset', 'Tilbakestill', 'Réinitialiser', 'Restablir', 'Nulstil'),
    trad(169, 'config.fichaMedica', 'config',
      'Ficha médica', 'Medical record', 'Medisinsk kort', 'Fiche médicale', 'Fitxa mèdica', 'Medicinsk kort'),
    trad(170, 'config.eliminarDatos', 'config',
      'Eliminar datos guardados localmente', 'Delete locally saved data',
      'Slett lokalt lagrede data', 'Supprimer les données enregistrées localement',
      'Eliminar dades guardades localment', 'Slet lokalt gemte data'),
    trad(171, 'config.borrar', 'config',
      'Borrar', 'Delete', 'Slett', 'Supprimer', 'Esborrar', 'Slet'),
    trad(172, 'config.acercaDe', 'config',
      'Acerca de la aplicación', 'About the app',
      'Om appen', 'À propos de l\'application', 'Sobre l\'aplicació', 'Om appen'),
    trad(173, 'config.version', 'config',
      'Versión', 'Version', 'Versjon', 'Version', 'Versió', 'Version'),
    trad(174, 'config.autor', 'config',
      'Autor', 'Author', 'Forfatter', 'Auteur', 'Autor', 'Forfatter'),
    trad(175, 'config.proyecto', 'config',
      'Proyecto', 'Project', 'Prosjekt', 'Projet', 'Projecte', 'Projekt'),
    trad(176, 'config.tutor', 'config',
      'Tutor', 'Tutor', 'Veileder', 'Tuteur', 'Tutor', 'Vejleder'),
    trad(177, 'config.infoLegal', 'config',
      'Información legal', 'Legal information',
      'Juridisk informasjon', 'Informations légales', 'Informació legal', 'Juridisk information'),
    trad(178, 'config.avisoImportante', 'config',
      'Aviso importante', 'Important notice',
      'Viktig merknad', 'Avis important', 'Avís important', 'Vigtig meddelelse'),
    trad(179, 'config.avisoImportanteTexto', 'config',
      'Esta aplicación proporciona información orientativa de primeros auxilios. No sustituye la atención médica profesional ni la llamada al 112.',
      'This application provides guidance on first aid. It does not replace professional medical care or calling 112.',
      'Denne appen gir veiledende informasjon om førstehjelp. Den erstatter ikke profesjonell medisinsk hjelp eller oppringning til 112.',
      'Cette application fournit des informations indicatives de premiers secours. Elle ne remplace pas les soins médicaux professionnels ni l\'appel au 112.',
      'Aquesta aplicació proporciona informació orientativa de primers auxilis. No substitueix l\'atenció mèdica professional ni la trucada al 112.',
      'Denne app giver vejledende information om førstehjælp. Den erstatter ikke professionel lægehjælp eller opkald til 112.'),
    trad(180, 'config.privacidad', 'config',
      'Privacidad', 'Privacy', 'Personvern', 'Confidentialité', 'Privacitat', 'Privatliv'),
    trad(181, 'config.privacidadTexto', 'config',
      'La ficha médica y las observaciones de exploración se almacenan únicamente en tu dispositivo y no se envían a ningún servidor externo.',
      'The medical record and examination observations are stored only on your device and are not sent to any external server.',
      'Det medisinske kortet og undersøkelsesobservasjoner lagres kun på enheten din og sendes ikke til noen ekstern server.',
      'La fiche médicale et les observations d\'examen sont stockées uniquement sur votre appareil et ne sont pas envoyées à un serveur externe.',
      'La fitxa mèdica i les observacions d\'exploració s\'emmagatzemen únicament al teu dispositiu i no s\'envien a cap servidor extern.',
      'Det medicinske kort og undersøgelsesobservationer gemmes kun på din enhed og sendes ikke til nogen ekstern server.'),
    trad(182, 'config.sincContenido', 'config',
      'Sincronización de contenido', 'Content synchronization',
      'Innholdssynkronisering', 'Synchronisation du contenu',
      'Sincronització de contingut', 'Indholdssynkronisering'),
    trad(183, 'config.sincContenidoTexto', 'config',
      'Las guías y el árbol de emergencias se sincronizan con el servidor para mantenerse actualizados. No se recogen datos personales.',
      'The guides and emergency decision tree are synchronized with the server to stay updated. No personal data is collected.',
      'Guidene og nødtredet synkroniseres med serveren for å holde seg oppdatert. Ingen personlige data samles inn.',
      'Les guides et l\'arbre d\'urgences sont synchronisés avec le serveur pour rester à jour. Aucune donnée personnelle n\'est collectée.',
      'Les guies i l\'arbre d\'emergències se sincronitzen amb el servidor per mantenir-se actualitzats. No es recullen dades personals.',
      'Guiderne og nødtræet synkroniseres med serveren for at holde sig opdateret. Der indsamles ingen personlige data.'),
    trad(184, 'config.cargandoIdiomas', 'config',
      'Cargando idiomas...', 'Loading languages...',
      'Laster inn språk...', 'Chargement des langues...', 'Carregant idiomes...', 'Indlæser sprog...'),
  ]);
  console.log('✓ Configuración (152-184)');

  // diálogos (185-192)
  await Promise.all([
    trad(185, 'dialog.cancelar', 'dialog',
      'Cancelar', 'Cancel', 'Avbryt', 'Annuler', 'Cancel·lar', 'Annuller'),
    trad(186, 'dialog.confirmar', 'dialog',
      'Confirmar', 'Confirm', 'Bekreft', 'Confirmer', 'Confirmar', 'Bekræft'),
    trad(187, 'dialog.restablecerTitulo', 'dialog',
      'Restablecer aviso legal', 'Reset legal notice',
      'Tilbakestill juridisk merknad', 'Réinitialiser les mentions légales',
      'Restablir avís legal', 'Nulstil juridisk meddelelse'),
    trad(188, 'dialog.restablecerTexto', 'dialog',
      'El aviso legal se mostrará de nuevo la próxima vez que abras la aplicación. ¿Continuar?',
      'The legal notice will be shown again the next time you open the app. Continue?',
      'Den juridiske merknaden vises igjen neste gang du åpner appen. Fortsette?',
      'Les mentions légales s\'afficheront à nouveau la prochaine fois que vous ouvrirez l\'application. Continuer ?',
      'L\'avís legal es mostrarà de nou la propera vegada que obris l\'aplicació. Continuar?',
      'Den juridiske meddelelse vises igen næste gang du åbner appen. Fortsæt?'),
    trad(189, 'dialog.restablecidoMsg', 'dialog',
      'Aviso legal restablecido. Se mostrará al reiniciar la app.',
      'Legal notice reset. It will be shown on app restart.',
      'Juridisk merknad tilbakestilt. Vises ved omstart av appen.',
      'Mentions légales réinitialisées. Elles s\'afficheront au redémarrage de l\'app.',
      'Avís legal restablit. Es mostrarà en reiniciar l\'app.',
      'Juridisk meddelelse nulstillet. Vises ved genstart af appen.'),
    trad(190, 'dialog.borrarFichaTitulo', 'dialog',
      'Borrar ficha médica', 'Delete medical record',
      'Slett medisinsk kort', 'Supprimer la fiche médicale', 'Esborrar fitxa mèdica', 'Slet medicinsk kort'),
    trad(191, 'dialog.borrarFichaTexto', 'dialog',
      'Se eliminarán todos los datos de tu ficha médica guardados en el dispositivo. Esta acción no se puede deshacer.',
      'All your medical record data saved on your device will be deleted. This action cannot be undone.',
      'Alle data fra det medisinske kortet ditt lagret på enheten vil bli slettet. Denne handlingen kan ikke angres.',
      'Toutes les données de votre fiche médicale enregistrées sur l\'appareil seront supprimées. Cette action ne peut pas être annulée.',
      'S\'eliminaran totes les dades de la teva fitxa mèdica guardades al dispositiu. Aquesta acció no es pot desfer.',
      'Alle data fra dit medicinske kort gemt på enheden vil blive slettet. Denne handling kan ikke fortrydes.'),
    trad(192, 'dialog.fichaEliminada', 'dialog',
      'Ficha médica eliminada.', 'Medical record deleted.',
      'Medisinsk kort slettet.', 'Fiche médicale supprimée.', 'Fitxa mèdica eliminada.', 'Medicinsk kort slettet.'),
  ]);
  console.log('✓ Diálogos (185-192)');

  console.log('\n✅ 192 claves (1-192) actualizadas con idiomas es/en/no/fr/ca/da en Firestore.');
  process.exit(0);
}

migrate().catch((err) => {
  console.error('❌ Error:', err);
  process.exit(1);
});
